using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PICkit2V3
{
	public partial class DialogUART : Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.components = new Container();
			ComponentResourceManager resources = new ComponentResourceManager(typeof(PICkit2V3.DialogUART));
			this.textBoxDisplay = new TextBox();
			this.pictureBox1 = new PictureBox();
			this.label1 = new Label();
			this.radioButtonConnect = new RadioButton();
			this.radioButtonDisconnect = new RadioButton();
			this.comboBoxBaud = new ComboBox();
			this.panel1 = new Panel();
			this.panel2 = new Panel();
			this.radioButtonHex = new RadioButton();
			this.radioButtonASCII = new RadioButton();
			this.label2 = new Label();
			this.label3 = new Label();
			this.textBoxString1 = new TextBox();
			this.buttonString1 = new Button();
			this.buttonString2 = new Button();
			this.textBoxString2 = new TextBox();
			this.buttonString4 = new Button();
			this.buttonString3 = new Button();
			this.textBoxString3 = new TextBox();
			this.textBoxString4 = new TextBox();
			this.buttonLog = new Button();
			this.buttonClearScreen = new Button();
			this.buttonExit = new Button();
			this.checkBoxEcho = new CheckBox();
			this.labelMacros = new Label();
			this.timerPollForData = new Timer(this.components);
			this.label5 = new Label();
			this.checkBoxCRLF = new CheckBox();
			this.saveFileDialogLogFile = new SaveFileDialog();
			this.checkBoxWrap = new CheckBox();
			this.pictureBoxHelp = new PictureBox();
			this.checkBoxVDD = new CheckBox();
			this.panelVdd = new Panel();
			this.labelTypeHex = new Label();
			((ISupportInitialize)this.pictureBox1).BeginInit();
			this.panel1.SuspendLayout();
			this.panel2.SuspendLayout();
			((ISupportInitialize)this.pictureBoxHelp).BeginInit();
			this.panelVdd.SuspendLayout();
			base.SuspendLayout();
			this.textBoxDisplay.Anchor = (AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
			this.textBoxDisplay.BackColor = SystemColors.Window;
			this.textBoxDisplay.Cursor = Cursors.Default;
			this.textBoxDisplay.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.textBoxDisplay.Location = new Point(13, 44);
			this.textBoxDisplay.MaxLength = 17220;
			this.textBoxDisplay.MinimumSize = new Size(708, 332);
			this.textBoxDisplay.Multiline = true;
			this.textBoxDisplay.Name = "textBoxDisplay";
			this.textBoxDisplay.ReadOnly = true;
			this.textBoxDisplay.ScrollBars = ScrollBars.Both;
			this.textBoxDisplay.Size = new Size(708, 332);
			this.textBoxDisplay.TabIndex = 0;
			this.textBoxDisplay.Leave += new EventHandler(this.TextBoxDisplay_Leave);
			this.pictureBox1.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.pictureBox1.Image = (Image)resources.GetObject("pictureBox1.Image");
			this.pictureBox1.Location = new Point(13, 385);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new Size(189, 116);
			this.pictureBox1.SizeMode = PictureBoxSizeMode.AutoSize;
			this.pictureBox1.TabIndex = 1;
			this.pictureBox1.TabStop = false;
			this.label1.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.label1.AutoSize = true;
			this.label1.Location = new Point(10, 504);
			this.label1.Name = "label1";
			this.label1.Size = new Size(181, 13);
			this.label1.TabIndex = 2;
			this.label1.Text = "Connect PICkit 2 VDD && target VDD.";
			this.radioButtonConnect.Appearance = Appearance.Button;
			this.radioButtonConnect.AutoCheck = false;
			this.radioButtonConnect.Location = new Point(130, 4);
			this.radioButtonConnect.Name = "radioButtonConnect";
			this.radioButtonConnect.Size = new Size(70, 22);
			this.radioButtonConnect.TabIndex = 14;
			this.radioButtonConnect.Text = "Connect";
			this.radioButtonConnect.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonConnect.UseVisualStyleBackColor = true;
			this.radioButtonConnect.Click += new EventHandler(this.RadioButtonConnect_Click_1);
			this.radioButtonDisconnect.Appearance = Appearance.Button;
			this.radioButtonDisconnect.AutoCheck = false;
			this.radioButtonDisconnect.Checked = true;
			this.radioButtonDisconnect.Location = new Point(206, 4);
			this.radioButtonDisconnect.Name = "radioButtonDisconnect";
			this.radioButtonDisconnect.Size = new Size(70, 22);
			this.radioButtonDisconnect.TabIndex = 15;
			this.radioButtonDisconnect.TabStop = true;
			this.radioButtonDisconnect.Text = "Disconnect";
			this.radioButtonDisconnect.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonDisconnect.UseVisualStyleBackColor = true;
			this.radioButtonDisconnect.Click += new EventHandler(this.RadioButtonDisconnect_Click);
			this.comboBoxBaud.BackColor = SystemColors.Info;
			this.comboBoxBaud.DropDownStyle = ComboBoxStyle.DropDownList;
			this.comboBoxBaud.FormattingEnabled = true;
			this.comboBoxBaud.Items.AddRange(new object[]
			{
				"- Select Baud -"
			});
			this.comboBoxBaud.Location = new Point(6, 5);
			this.comboBoxBaud.MaxDropDownItems = 12;
			this.comboBoxBaud.Name = "comboBoxBaud";
			this.comboBoxBaud.Size = new Size(118, 21);
			this.comboBoxBaud.TabIndex = 13;
			this.comboBoxBaud.SelectedIndexChanged += new EventHandler(this.ComboBoxBaud_SelectedIndexChanged);
			this.panel1.Controls.Add(this.comboBoxBaud);
			this.panel1.Controls.Add(this.radioButtonDisconnect);
			this.panel1.Controls.Add(this.radioButtonConnect);
			this.panel1.Location = new Point(13, 8);
			this.panel1.Name = "panel1";
			this.panel1.Size = new Size(280, 30);
			this.panel1.TabIndex = 6;
			this.panel2.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
			this.panel2.Controls.Add(this.radioButtonHex);
			this.panel2.Controls.Add(this.radioButtonASCII);
			this.panel2.Location = new Point(618, 9);
			this.panel2.Name = "panel2";
			this.panel2.Size = new Size(106, 29);
			this.panel2.TabIndex = 7;
			this.radioButtonHex.Appearance = Appearance.Button;
			this.radioButtonHex.Location = new Point(57, 3);
			this.radioButtonHex.Name = "radioButtonHex";
			this.radioButtonHex.Size = new Size(47, 22);
			this.radioButtonHex.TabIndex = 17;
			this.radioButtonHex.Text = "Hex";
			this.radioButtonHex.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonHex.UseVisualStyleBackColor = true;
			this.radioButtonHex.CheckedChanged += new EventHandler(this.RadioButtonHex_CheckedChanged);
			this.radioButtonASCII.Appearance = Appearance.Button;
			this.radioButtonASCII.Checked = true;
			this.radioButtonASCII.Location = new Point(3, 3);
			this.radioButtonASCII.Name = "radioButtonASCII";
			this.radioButtonASCII.Size = new Size(47, 22);
			this.radioButtonASCII.TabIndex = 16;
			this.radioButtonASCII.TabStop = true;
			this.radioButtonASCII.Text = "ASCII";
			this.radioButtonASCII.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonASCII.UseVisualStyleBackColor = true;
			this.radioButtonASCII.CheckedChanged += new EventHandler(this.RadioButtonASCII_CheckedChanged);
			this.label2.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
			this.label2.AutoSize = true;
			this.label2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label2.Location = new Point(570, 14);
			this.label2.Name = "label2";
			this.label2.Size = new Size(47, 15);
			this.label2.TabIndex = 8;
			this.label2.Text = "Mode:";
			this.label3.AutoSize = true;
			this.label3.Location = new Point(363, 8);
			this.label3.Name = "label3";
			this.label3.Size = new Size(164, 13);
			this.label3.TabIndex = 9;
			this.label3.Text = "8 data bits - No parity - 1 Stop bit.";
			this.textBoxString1.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
			this.textBoxString1.BackColor = SystemColors.Info;
			this.textBoxString1.Font = new Font("Courier New", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.textBoxString1.Location = new Point(306, 406);
			this.textBoxString1.Name = "textBoxString1";
			this.textBoxString1.Size = new Size(286, 20);
			this.textBoxString1.TabIndex = 1;
			this.textBoxString1.TextChanged += new EventHandler(this.TextBoxString1_TextChanged);
			this.buttonString1.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.buttonString1.Enabled = false;
			this.buttonString1.Location = new Point(246, 404);
			this.buttonString1.Name = "buttonString1";
			this.buttonString1.Size = new Size(54, 22);
			this.buttonString1.TabIndex = 5;
			this.buttonString1.Text = "Send";
			this.buttonString1.UseVisualStyleBackColor = true;
			this.buttonString1.Click += new EventHandler(this.ButtonString1_Click);
			this.buttonString2.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.buttonString2.Enabled = false;
			this.buttonString2.Location = new Point(246, 434);
			this.buttonString2.Name = "buttonString2";
			this.buttonString2.Size = new Size(54, 22);
			this.buttonString2.TabIndex = 6;
			this.buttonString2.Text = "Send";
			this.buttonString2.UseVisualStyleBackColor = true;
			this.buttonString2.Click += new EventHandler(this.ButtonString2_Click);
			this.textBoxString2.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
			this.textBoxString2.BackColor = SystemColors.Info;
			this.textBoxString2.Font = new Font("Courier New", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.textBoxString2.Location = new Point(306, 435);
			this.textBoxString2.Name = "textBoxString2";
			this.textBoxString2.Size = new Size(286, 20);
			this.textBoxString2.TabIndex = 2;
			this.textBoxString2.TextChanged += new EventHandler(this.TextBoxString2_TextChanged);
			this.buttonString4.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.buttonString4.Enabled = false;
			this.buttonString4.Location = new Point(246, 490);
			this.buttonString4.Name = "buttonString4";
			this.buttonString4.Size = new Size(54, 22);
			this.buttonString4.TabIndex = 8;
			this.buttonString4.Text = "Send";
			this.buttonString4.UseVisualStyleBackColor = true;
			this.buttonString4.Click += new EventHandler(this.ButtonString4_Click);
			this.buttonString3.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.buttonString3.Enabled = false;
			this.buttonString3.Location = new Point(246, 462);
			this.buttonString3.Name = "buttonString3";
			this.buttonString3.Size = new Size(54, 22);
			this.buttonString3.TabIndex = 7;
			this.buttonString3.Text = "Send";
			this.buttonString3.UseVisualStyleBackColor = true;
			this.buttonString3.Click += new EventHandler(this.ButtonString3_Click);
			this.textBoxString3.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
			this.textBoxString3.BackColor = SystemColors.Info;
			this.textBoxString3.Font = new Font("Courier New", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.textBoxString3.Location = new Point(306, 464);
			this.textBoxString3.Name = "textBoxString3";
			this.textBoxString3.Size = new Size(286, 20);
			this.textBoxString3.TabIndex = 3;
			this.textBoxString3.TextChanged += new EventHandler(this.TextBoxString3_TextChanged);
			this.textBoxString4.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right);
			this.textBoxString4.BackColor = SystemColors.Info;
			this.textBoxString4.Font = new Font("Courier New", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.textBoxString4.Location = new Point(306, 492);
			this.textBoxString4.Name = "textBoxString4";
			this.textBoxString4.Size = new Size(286, 20);
			this.textBoxString4.TabIndex = 4;
			this.textBoxString4.TextChanged += new EventHandler(this.TextBoxString4_TextChanged);
			this.buttonLog.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
			this.buttonLog.Location = new Point(618, 404);
			this.buttonLog.Name = "buttonLog";
			this.buttonLog.Size = new Size(102, 22);
			this.buttonLog.TabIndex = 9;
			this.buttonLog.Text = "Log to File";
			this.buttonLog.UseVisualStyleBackColor = true;
			this.buttonLog.Click += new EventHandler(this.ButtonLog_Click);
			this.buttonClearScreen.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
			this.buttonClearScreen.Location = new Point(618, 434);
			this.buttonClearScreen.Name = "buttonClearScreen";
			this.buttonClearScreen.Size = new Size(102, 22);
			this.buttonClearScreen.TabIndex = 10;
			this.buttonClearScreen.Text = "Clear Screen";
			this.buttonClearScreen.UseVisualStyleBackColor = true;
			this.buttonClearScreen.Click += new EventHandler(this.ButtonClearScreen_Click);
			this.buttonExit.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
			this.buttonExit.Location = new Point(618, 490);
			this.buttonExit.Name = "buttonExit";
			this.buttonExit.Size = new Size(102, 22);
			this.buttonExit.TabIndex = 12;
			this.buttonExit.Text = "Exit UART Tool";
			this.buttonExit.UseVisualStyleBackColor = true;
			this.buttonExit.Click += new EventHandler(this.ButtonExit_Click);
			this.checkBoxEcho.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
			this.checkBoxEcho.AutoSize = true;
			this.checkBoxEcho.Checked = true;
			this.checkBoxEcho.CheckState = CheckState.Checked;
			this.checkBoxEcho.Location = new Point(638, 466);
			this.checkBoxEcho.Name = "checkBoxEcho";
			this.checkBoxEcho.Size = new Size(68, 17);
			this.checkBoxEcho.TabIndex = 11;
			this.checkBoxEcho.Text = "Echo On";
			this.checkBoxEcho.UseVisualStyleBackColor = true;
			this.labelMacros.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.labelMacros.AutoSize = true;
			this.labelMacros.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelMacros.Location = new Point(243, 382);
			this.labelMacros.Name = "labelMacros";
			this.labelMacros.Size = new Size(100, 15);
			this.labelMacros.TabIndex = 22;
			this.labelMacros.Text = "String Macros:";
			this.timerPollForData.Interval = 15;
			this.timerPollForData.Tick += new EventHandler(this.TimerPollForData_Tick);
			this.label5.AutoSize = true;
			this.label5.Location = new Point(375, 22);
			this.label5.Name = "label5";
			this.label5.Size = new Size(137, 13);
			this.label5.TabIndex = 23;
			this.label5.Text = "ASCII newline = 0x0D 0x0A";
			this.checkBoxCRLF.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.checkBoxCRLF.AutoSize = true;
			this.checkBoxCRLF.Checked = true;
			this.checkBoxCRLF.CheckState = CheckState.Checked;
			this.checkBoxCRLF.Location = new Point(365, 383);
			this.checkBoxCRLF.Name = "checkBoxCRLF";
			this.checkBoxCRLF.Size = new Size(157, 17);
			this.checkBoxCRLF.TabIndex = 18;
			this.checkBoxCRLF.Text = "Append CR+LF (x0D + x0A)";
			this.checkBoxCRLF.UseVisualStyleBackColor = true;
			this.saveFileDialogLogFile.DefaultExt = "txt";
			this.saveFileDialogLogFile.Filter = "All files|*.*|Text files|*.txt";
			this.saveFileDialogLogFile.InitialDirectory = "c:\\";
			this.saveFileDialogLogFile.Title = "Log UART data to file";
			this.saveFileDialogLogFile.FileOk += new CancelEventHandler(this.SaveFileDialogLogFile_FileOk);
			this.checkBoxWrap.Anchor = (AnchorStyles.Bottom | AnchorStyles.Right);
			this.checkBoxWrap.AutoSize = true;
			this.checkBoxWrap.Checked = true;
			this.checkBoxWrap.CheckState = CheckState.Checked;
			this.checkBoxWrap.Location = new Point(638, 383);
			this.checkBoxWrap.Name = "checkBoxWrap";
			this.checkBoxWrap.Size = new Size(76, 17);
			this.checkBoxWrap.TabIndex = 24;
			this.checkBoxWrap.Text = "Wrap Text";
			this.checkBoxWrap.UseVisualStyleBackColor = true;
			this.checkBoxWrap.CheckedChanged += new EventHandler(this.CheckBoxWrap_CheckedChanged);
			this.pictureBoxHelp.Cursor = Cursors.Hand;
			this.pictureBoxHelp.Image = (Image)resources.GetObject("pictureBoxHelp.Image");
			this.pictureBoxHelp.Location = new Point(540, 10);
			this.pictureBoxHelp.Name = "pictureBoxHelp";
			this.pictureBoxHelp.Size = new Size(24, 24);
			this.pictureBoxHelp.TabIndex = 26;
			this.pictureBoxHelp.TabStop = false;
			this.pictureBoxHelp.Click += new EventHandler(this.PictureBoxHelp_Click);
			this.checkBoxVDD.AutoSize = true;
			this.checkBoxVDD.Location = new Point(6, 5);
			this.checkBoxVDD.Name = "checkBoxVDD";
			this.checkBoxVDD.Size = new Size(49, 17);
			this.checkBoxVDD.TabIndex = 27;
			this.checkBoxVDD.Text = "VDD";
			this.checkBoxVDD.UseVisualStyleBackColor = true;
			this.checkBoxVDD.Click += new EventHandler(this.CheckBoxVDD_Click);
			this.panelVdd.Controls.Add(this.checkBoxVDD);
			this.panelVdd.Location = new Point(299, 10);
			this.panelVdd.Name = "panelVdd";
			this.panelVdd.Size = new Size(65, 27);
			this.panelVdd.TabIndex = 28;
			this.labelTypeHex.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.labelTypeHex.AutoSize = true;
			this.labelTypeHex.ForeColor = SystemColors.ControlDarkDark;
			this.labelTypeHex.Location = new Point(520, 384);
			this.labelTypeHex.Name = "labelTypeHex";
			this.labelTypeHex.Size = new Size(75, 13);
			this.labelTypeHex.TabIndex = 29;
			this.labelTypeHex.Text = "Type Hex : A_";
			this.labelTypeHex.Visible = false;
			base.AutoScaleDimensions = new SizeF(96f, 96f);
			base.AutoScaleMode = AutoScaleMode.Dpi;
			base.ClientSize = new Size(736, 526);
			base.Controls.Add(this.labelTypeHex);
			base.Controls.Add(this.panelVdd);
			base.Controls.Add(this.pictureBoxHelp);
			base.Controls.Add(this.checkBoxWrap);
			base.Controls.Add(this.checkBoxCRLF);
			base.Controls.Add(this.label5);
			base.Controls.Add(this.labelMacros);
			base.Controls.Add(this.checkBoxEcho);
			base.Controls.Add(this.buttonExit);
			base.Controls.Add(this.buttonClearScreen);
			base.Controls.Add(this.buttonLog);
			base.Controls.Add(this.textBoxString4);
			base.Controls.Add(this.textBoxString3);
			base.Controls.Add(this.buttonString3);
			base.Controls.Add(this.buttonString4);
			base.Controls.Add(this.textBoxString2);
			base.Controls.Add(this.buttonString2);
			base.Controls.Add(this.buttonString1);
			base.Controls.Add(this.textBoxString1);
			base.Controls.Add(this.label3);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.panel2);
			base.Controls.Add(this.panel1);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.pictureBox1);
			base.Controls.Add(this.textBoxDisplay);
			base.KeyPreview = true;
			this.MinimumSize = new Size(744, 559);
			base.Name = "DialogUART";
			base.StartPosition = FormStartPosition.CenterScreen;
			this.Text = "PICkit 2 UART Tool";
			base.FormClosing += new FormClosingEventHandler(this.DialogUART_FormClosing);
			((ISupportInitialize)this.pictureBox1).EndInit();
			this.panel1.ResumeLayout(false);
			this.panel2.ResumeLayout(false);
			((ISupportInitialize)this.pictureBoxHelp).EndInit();
			this.panelVdd.ResumeLayout(false);
			this.panelVdd.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		private IContainer components;
		private TextBox textBoxDisplay;
		private PictureBox pictureBox1;
		private Label label1;
		private RadioButton radioButtonConnect;
		private RadioButton radioButtonDisconnect;
		private ComboBox comboBoxBaud;
		private Panel panel1;
		private Panel panel2;
		private RadioButton radioButtonHex;
		private RadioButton radioButtonASCII;
		private Label label2;
		private Label label3;
		private TextBox textBoxString1;
		private Button buttonString1;
		private Button buttonString2;
		private TextBox textBoxString2;
		private Button buttonString4;
		private Button buttonString3;
		private TextBox textBoxString3;
		private TextBox textBoxString4;
		private Button buttonLog;
		private Button buttonClearScreen;
		private Button buttonExit;
		private CheckBox checkBoxEcho;
		private Label labelMacros;
		private Timer timerPollForData;
		private Label label5;
		private CheckBox checkBoxCRLF;
		private SaveFileDialog saveFileDialogLogFile;
		private CheckBox checkBoxWrap;
		private PictureBox pictureBoxHelp;
		private CheckBox checkBoxVDD;
		private Panel panelVdd;
		private Label labelTypeHex;
	}
}
