using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PICkit2V3
{
	public partial class DialogLogic : Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.components = new Container();
			ComponentResourceManager resources = new ComponentResourceManager(typeof(PICkit2V3.DialogLogic));
			this.label2 = new Label();
			this.panel2 = new Panel();
			this.radioButtonAnalyzer = new RadioButton();
			this.radioButtonLogicIO = new RadioButton();
			this.panelAnalyzer = new Panel();
			this.buttonSave = new Button();
			this.labelCursor1Val = new Label();
			this.labelCursor1 = new Label();
			this.labelCursorDelta = new Label();
			this.labelCursorDeltaVal = new Label();
			this.labelCursor2 = new Label();
			this.checkBoxCursors = new CheckBox();
			this.labelCursor2Val = new Label();
			this.label24 = new Label();
			this.label23 = new Label();
			this.label22 = new Label();
			this.groupBox2 = new GroupBox();
			this.label25 = new Label();
			this.radioButtonTrigDly3 = new RadioButton();
			this.radioButtonTrigDly2 = new RadioButton();
			this.radioButtonTrigDly1 = new RadioButton();
			this.radioButtonTrigEnd = new RadioButton();
			this.radioButtonTrigMid = new RadioButton();
			this.radioButtonTrigStart = new RadioButton();
			this.label21 = new Label();
			this.labelAliasFreq = new Label();
			this.comboBoxSampleRate = new ComboBox();
			this.label19 = new Label();
			this.buttonRun = new Button();
			this.pictureBox1 = new PictureBox();
			this.groupBox1 = new GroupBox();
			this.label18 = new Label();
			this.label17 = new Label();
			this.label15 = new Label();
			this.textBox1 = new TextBox();
			this.label5 = new Label();
			this.label16 = new Label();
			this.label6 = new Label();
			this.label7 = new Label();
			this.label14 = new Label();
			this.comboBoxCh1Trig = new ComboBox();
			this.label13 = new Label();
			this.comboBoxCh2Trig = new ComboBox();
			this.label12 = new Label();
			this.comboBoxCh3Trig = new ComboBox();
			this.label11 = new Label();
			this.label8 = new Label();
			this.label10 = new Label();
			this.label9 = new Label();
			this.groupBoxZoom = new GroupBox();
			this.radioButton4x = new RadioButton();
			this.radioButtonZoom05 = new RadioButton();
			this.radioButton2x = new RadioButton();
			this.radioButtonZoom1x = new RadioButton();
			this.labelTimeScale = new Label();
			this.label4 = new Label();
			this.label3 = new Label();
			this.label1 = new Label();
			this.panelDisplay = new Panel();
			this.pictureBoxDisplay = new PictureBox();
			this.buttonExit = new Button();
			this.buttonHelp = new Button();
			this.timerRun = new Timer(this.components);
			this.saveFileDialogDisplay = new SaveFileDialog();
			this.panelLogicIO = new Panel();
			this.checkBoxIOEnable = new CheckBox();
			this.labelOut6Click = new Label();
			this.labelOut5Click = new Label();
			this.labelOut4Click = new Label();
			this.labelOut1Click = new Label();
			this.textBoxPin6Out = new TextBox();
			this.textBoxPin6In = new TextBox();
			this.textBoxPin5Out = new TextBox();
			this.textBoxPin5In = new TextBox();
			this.textBoxPin4Out = new TextBox();
			this.textBoxPin1Out = new TextBox();
			this.label34 = new Label();
			this.label33 = new Label();
			this.textBoxPin4In = new TextBox();
			this.label32 = new Label();
			this.label31 = new Label();
			this.panel4 = new Panel();
			this.radioButtonPin6In = new RadioButton();
			this.radioButtonPin6Out = new RadioButton();
			this.panel3 = new Panel();
			this.radioButtonPin5In = new RadioButton();
			this.radioButtonPin5Out = new RadioButton();
			this.panel1 = new Panel();
			this.radioButtonPin4In = new RadioButton();
			this.radioButtonPin4Out = new RadioButton();
			this.label30 = new Label();
			this.label29 = new Label();
			this.label28 = new Label();
			this.label27 = new Label();
			this.label26 = new Label();
			this.label20 = new Label();
			this.pictureBox2 = new PictureBox();
			this.timerIO = new Timer(this.components);
			this.checkBoxVDD = new CheckBox();
			this.panel2.SuspendLayout();
			this.panelAnalyzer.SuspendLayout();
			this.groupBox2.SuspendLayout();
			((ISupportInitialize)this.pictureBox1).BeginInit();
			this.groupBox1.SuspendLayout();
			this.groupBoxZoom.SuspendLayout();
			this.panelDisplay.SuspendLayout();
			((ISupportInitialize)this.pictureBoxDisplay).BeginInit();
			this.panelLogicIO.SuspendLayout();
			this.panel4.SuspendLayout();
			this.panel3.SuspendLayout();
			this.panel1.SuspendLayout();
			((ISupportInitialize)this.pictureBox2).BeginInit();
			base.SuspendLayout();
			this.label2.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
			this.label2.AutoSize = true;
			this.label2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label2.Location = new Point(442, 15);
			this.label2.Name = "label2";
			this.label2.Size = new Size(47, 15);
			this.label2.TabIndex = 10;
			this.label2.Text = "Mode:";
			this.panel2.Anchor = (AnchorStyles.Top | AnchorStyles.Right);
			this.panel2.Controls.Add(this.radioButtonAnalyzer);
			this.panel2.Controls.Add(this.radioButtonLogicIO);
			this.panel2.Location = new Point(494, 9);
			this.panel2.Name = "panel2";
			this.panel2.Size = new Size(130, 30);
			this.panel2.TabIndex = 9;
			this.radioButtonAnalyzer.Appearance = Appearance.Button;
			this.radioButtonAnalyzer.Location = new Point(69, 2);
			this.radioButtonAnalyzer.Name = "radioButtonAnalyzer";
			this.radioButtonAnalyzer.Size = new Size(60, 22);
			this.radioButtonAnalyzer.TabIndex = 17;
			this.radioButtonAnalyzer.Text = "Analyzer";
			this.radioButtonAnalyzer.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonAnalyzer.UseVisualStyleBackColor = true;
			this.radioButtonAnalyzer.CheckedChanged += new EventHandler(this.RadioButtonAnalyzer_CheckedChanged);
			this.radioButtonLogicIO.Appearance = Appearance.Button;
			this.radioButtonLogicIO.Checked = true;
			this.radioButtonLogicIO.Location = new Point(3, 2);
			this.radioButtonLogicIO.Name = "radioButtonLogicIO";
			this.radioButtonLogicIO.Size = new Size(60, 22);
			this.radioButtonLogicIO.TabIndex = 16;
			this.radioButtonLogicIO.TabStop = true;
			this.radioButtonLogicIO.Text = "Logic I/O";
			this.radioButtonLogicIO.TextAlign = ContentAlignment.MiddleCenter;
			this.radioButtonLogicIO.UseVisualStyleBackColor = true;
			this.panelAnalyzer.Controls.Add(this.buttonSave);
			this.panelAnalyzer.Controls.Add(this.labelCursor1Val);
			this.panelAnalyzer.Controls.Add(this.labelCursor1);
			this.panelAnalyzer.Controls.Add(this.labelCursorDelta);
			this.panelAnalyzer.Controls.Add(this.labelCursorDeltaVal);
			this.panelAnalyzer.Controls.Add(this.labelCursor2);
			this.panelAnalyzer.Controls.Add(this.checkBoxCursors);
			this.panelAnalyzer.Controls.Add(this.labelCursor2Val);
			this.panelAnalyzer.Controls.Add(this.label24);
			this.panelAnalyzer.Controls.Add(this.label23);
			this.panelAnalyzer.Controls.Add(this.label22);
			this.panelAnalyzer.Controls.Add(this.groupBox2);
			this.panelAnalyzer.Controls.Add(this.pictureBox1);
			this.panelAnalyzer.Controls.Add(this.groupBox1);
			this.panelAnalyzer.Controls.Add(this.groupBoxZoom);
			this.panelAnalyzer.Controls.Add(this.labelTimeScale);
			this.panelAnalyzer.Controls.Add(this.label4);
			this.panelAnalyzer.Controls.Add(this.label3);
			this.panelAnalyzer.Controls.Add(this.label1);
			this.panelAnalyzer.Controls.Add(this.panelDisplay);
			this.panelAnalyzer.Location = new Point(12, 39);
			this.panelAnalyzer.Name = "panelAnalyzer";
			this.panelAnalyzer.Size = new Size(610, 326);
			this.panelAnalyzer.TabIndex = 11;
			this.panelAnalyzer.Visible = false;
			this.buttonSave.Location = new Point(542, 119);
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.Size = new Size(68, 23);
			this.buttonSave.TabIndex = 34;
			this.buttonSave.Text = "Save";
			this.buttonSave.UseVisualStyleBackColor = true;
			this.buttonSave.Click += new EventHandler(this.ButtonSave_Click);
			this.labelCursor1Val.AutoSize = true;
			this.labelCursor1Val.Enabled = false;
			this.labelCursor1Val.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursor1Val.ForeColor = Color.RoyalBlue;
			this.labelCursor1Val.Location = new Point(260, 2);
			this.labelCursor1Val.Name = "labelCursor1Val";
			this.labelCursor1Val.Size = new Size(63, 13);
			this.labelCursor1Val.TabIndex = 29;
			this.labelCursor1Val.Text = "100.52 us";
			this.labelCursor1.AutoSize = true;
			this.labelCursor1.Enabled = false;
			this.labelCursor1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursor1.ForeColor = Color.RoyalBlue;
			this.labelCursor1.Location = new Point(237, 2);
			this.labelCursor1.Name = "labelCursor1";
			this.labelCursor1.Size = new Size(26, 13);
			this.labelCursor1.TabIndex = 28;
			this.labelCursor1.Text = "X =";
			this.labelCursorDelta.AutoSize = true;
			this.labelCursorDelta.Enabled = false;
			this.labelCursorDelta.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursorDelta.ForeColor = SystemColors.ControlText;
			this.labelCursorDelta.Location = new Point(439, 2);
			this.labelCursorDelta.Name = "labelCursorDelta";
			this.labelCursorDelta.Size = new Size(38, 13);
			this.labelCursorDelta.TabIndex = 32;
			this.labelCursorDelta.Text = "Y-X =";
			this.labelCursorDeltaVal.AutoSize = true;
			this.labelCursorDeltaVal.Enabled = false;
			this.labelCursorDeltaVal.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursorDeltaVal.ForeColor = SystemColors.ControlText;
			this.labelCursorDeltaVal.Location = new Point(477, 2);
			this.labelCursorDeltaVal.Name = "labelCursorDeltaVal";
			this.labelCursorDeltaVal.Size = new Size(122, 13);
			this.labelCursorDeltaVal.TabIndex = 33;
			this.labelCursorDeltaVal.Text = "100.26 us (9974 Hz)";
			this.labelCursor2.AutoSize = true;
			this.labelCursor2.Enabled = false;
			this.labelCursor2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursor2.ForeColor = Color.DarkViolet;
			this.labelCursor2.Location = new Point(338, 2);
			this.labelCursor2.Name = "labelCursor2";
			this.labelCursor2.Size = new Size(26, 13);
			this.labelCursor2.TabIndex = 29;
			this.labelCursor2.Text = "Y =";
			this.checkBoxCursors.AutoSize = true;
			this.checkBoxCursors.Location = new Point(161, 1);
			this.checkBoxCursors.Name = "checkBoxCursors";
			this.checkBoxCursors.Size = new Size(61, 17);
			this.checkBoxCursors.TabIndex = 30;
			this.checkBoxCursors.Text = "Cursors";
			this.checkBoxCursors.UseVisualStyleBackColor = true;
			this.checkBoxCursors.CheckedChanged += new EventHandler(this.CheckBoxCursors_CheckedChanged);
			this.labelCursor2Val.AutoSize = true;
			this.labelCursor2Val.Enabled = false;
			this.labelCursor2Val.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelCursor2Val.ForeColor = Color.DarkViolet;
			this.labelCursor2Val.Location = new Point(365, 2);
			this.labelCursor2Val.Name = "labelCursor2Val";
			this.labelCursor2Val.Size = new Size(63, 13);
			this.labelCursor2Val.TabIndex = 31;
			this.labelCursor2Val.Text = "200.78 us";
			this.label24.Anchor = (AnchorStyles.Bottom | AnchorStyles.Left);
			this.label24.AutoSize = true;
			this.label24.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label24.ForeColor = SystemColors.ActiveCaption;
			this.label24.Location = new Point(3, 297);
			this.label24.Name = "label24";
			this.label24.Size = new Size(117, 26);
			this.label24.TabIndex = 29;
			this.label24.Text = "Set VDD Voltage value\r\nin main form.";
			this.label23.AutoSize = true;
			this.label23.Location = new Point(84, 157);
			this.label23.Name = "label23";
			this.label23.Size = new Size(65, 78);
			this.label23.TabIndex = 28;
			this.label23.Text = "NOTE:\r\nCh 1 && Ch 2\r\ninputs have \r\n4.7k Ohm\r\npull-down\r\nresistors.";
			this.label22.AutoSize = true;
			this.label22.Location = new Point(3, 265);
			this.label22.Name = "label22";
			this.label22.Size = new Size(158, 26);
			this.label22.TabIndex = 27;
			this.label22.Text = "PICkit 2 VDD MUST connect to\r\ncircuit VDD.";
			this.groupBox2.Controls.Add(this.label25);
			this.groupBox2.Controls.Add(this.radioButtonTrigDly3);
			this.groupBox2.Controls.Add(this.radioButtonTrigDly2);
			this.groupBox2.Controls.Add(this.radioButtonTrigDly1);
			this.groupBox2.Controls.Add(this.radioButtonTrigEnd);
			this.groupBox2.Controls.Add(this.radioButtonTrigMid);
			this.groupBox2.Controls.Add(this.radioButtonTrigStart);
			this.groupBox2.Controls.Add(this.label21);
			this.groupBox2.Controls.Add(this.labelAliasFreq);
			this.groupBox2.Controls.Add(this.comboBoxSampleRate);
			this.groupBox2.Controls.Add(this.label19);
			this.groupBox2.Controls.Add(this.buttonRun);
			this.groupBox2.Location = new Point(359, 146);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new Size(251, 180);
			this.groupBox2.TabIndex = 26;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "Aquisition";
			this.label25.AutoSize = true;
			this.label25.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label25.Location = new Point(110, 164);
			this.label25.Name = "label25";
			this.label25.Size = new Size(135, 13);
			this.label25.TabIndex = 31;
			this.label25.Text = "1 Window = 1000 samples.";
			this.radioButtonTrigDly3.AutoSize = true;
			this.radioButtonTrigDly3.Location = new Point(126, 148);
			this.radioButtonTrigDly3.Name = "radioButtonTrigDly3";
			this.radioButtonTrigDly3.Size = new Size(108, 17);
			this.radioButtonTrigDly3.TabIndex = 30;
			this.radioButtonTrigDly3.Text = "Delay 3 Windows";
			this.radioButtonTrigDly3.UseVisualStyleBackColor = true;
			this.radioButtonTrigDly2.AutoSize = true;
			this.radioButtonTrigDly2.Location = new Point(126, 130);
			this.radioButtonTrigDly2.Name = "radioButtonTrigDly2";
			this.radioButtonTrigDly2.Size = new Size(108, 17);
			this.radioButtonTrigDly2.TabIndex = 29;
			this.radioButtonTrigDly2.Text = "Delay 2 Windows";
			this.radioButtonTrigDly2.UseVisualStyleBackColor = true;
			this.radioButtonTrigDly1.AutoSize = true;
			this.radioButtonTrigDly1.Location = new Point(126, 112);
			this.radioButtonTrigDly1.Name = "radioButtonTrigDly1";
			this.radioButtonTrigDly1.Size = new Size(103, 17);
			this.radioButtonTrigDly1.TabIndex = 28;
			this.radioButtonTrigDly1.Text = "Delay 1 Window";
			this.radioButtonTrigDly1.UseVisualStyleBackColor = true;
			this.radioButtonTrigEnd.AutoSize = true;
			this.radioButtonTrigEnd.Location = new Point(9, 148);
			this.radioButtonTrigEnd.Name = "radioButtonTrigEnd";
			this.radioButtonTrigEnd.Size = new Size(82, 17);
			this.radioButtonTrigEnd.TabIndex = 27;
			this.radioButtonTrigEnd.Text = "End of Data";
			this.radioButtonTrigEnd.UseVisualStyleBackColor = true;
			this.radioButtonTrigMid.AutoSize = true;
			this.radioButtonTrigMid.Location = new Point(9, 130);
			this.radioButtonTrigMid.Name = "radioButtonTrigMid";
			this.radioButtonTrigMid.Size = new Size(94, 17);
			this.radioButtonTrigMid.TabIndex = 26;
			this.radioButtonTrigMid.Text = "Center of Data";
			this.radioButtonTrigMid.UseVisualStyleBackColor = true;
			this.radioButtonTrigStart.AutoSize = true;
			this.radioButtonTrigStart.Checked = true;
			this.radioButtonTrigStart.Location = new Point(9, 112);
			this.radioButtonTrigStart.Name = "radioButtonTrigStart";
			this.radioButtonTrigStart.Size = new Size(85, 17);
			this.radioButtonTrigStart.TabIndex = 25;
			this.radioButtonTrigStart.TabStop = true;
			this.radioButtonTrigStart.Text = "Start of Data";
			this.radioButtonTrigStart.UseVisualStyleBackColor = true;
			this.label21.AutoSize = true;
			this.label21.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label21.Location = new Point(6, 89);
			this.label21.Name = "label21";
			this.label21.Size = new Size(113, 15);
			this.label21.TabIndex = 24;
			this.label21.Text = "Trigger Position:";
			this.labelAliasFreq.AutoSize = true;
			this.labelAliasFreq.Location = new Point(6, 63);
			this.labelAliasFreq.Name = "labelAliasFreq";
			this.labelAliasFreq.Size = new Size(224, 13);
			this.labelAliasFreq.TabIndex = 23;
			this.labelAliasFreq.Text = "NOTE: Signals greater than 500 kHz will alias.";
			this.comboBoxSampleRate.FormattingEnabled = true;
			this.comboBoxSampleRate.Items.AddRange(new object[]
			{
				"1 MHz - 1 ms Window",
				"500 kHz - 2 ms Window",
				"250 kHz - 4 ms Window",
				"100 kHz - 10 ms Window",
				"50 kHz - 20 ms Window",
				"25 kHz - 40 ms Window",
				"10 kHz - 100 ms Window",
				"5 kHz - 200 ms Window"
			});
			this.comboBoxSampleRate.Location = new Point(9, 37);
			this.comboBoxSampleRate.Name = "comboBoxSampleRate";
			this.comboBoxSampleRate.Size = new Size(168, 21);
			this.comboBoxSampleRate.TabIndex = 22;
			this.comboBoxSampleRate.SelectedIndexChanged += new EventHandler(this.ComboBoxSampleRate_SelectedIndexChanged);
			this.label19.AutoSize = true;
			this.label19.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label19.Location = new Point(6, 16);
			this.label19.Name = "label19";
			this.label19.Size = new Size(94, 15);
			this.label19.TabIndex = 21;
			this.label19.Text = "Sample Rate:";
			this.buttonRun.Location = new Point(189, 13);
			this.buttonRun.Name = "buttonRun";
			this.buttonRun.Size = new Size(56, 45);
			this.buttonRun.TabIndex = 0;
			this.buttonRun.Text = "RUN";
			this.buttonRun.UseVisualStyleBackColor = true;
			this.buttonRun.Click += new EventHandler(this.ButtonRun_Click);
			this.pictureBox1.Image = (Image)resources.GetObject("pictureBox1.Image");
			this.pictureBox1.Location = new Point(0, 146);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new Size(78, 116);
			this.pictureBox1.TabIndex = 25;
			this.pictureBox1.TabStop = false;
			this.groupBox1.Controls.Add(this.label18);
			this.groupBox1.Controls.Add(this.label17);
			this.groupBox1.Controls.Add(this.label15);
			this.groupBox1.Controls.Add(this.textBox1);
			this.groupBox1.Controls.Add(this.label5);
			this.groupBox1.Controls.Add(this.label16);
			this.groupBox1.Controls.Add(this.label6);
			this.groupBox1.Controls.Add(this.label7);
			this.groupBox1.Controls.Add(this.label14);
			this.groupBox1.Controls.Add(this.comboBoxCh1Trig);
			this.groupBox1.Controls.Add(this.label13);
			this.groupBox1.Controls.Add(this.comboBoxCh2Trig);
			this.groupBox1.Controls.Add(this.label12);
			this.groupBox1.Controls.Add(this.comboBoxCh3Trig);
			this.groupBox1.Controls.Add(this.label11);
			this.groupBox1.Controls.Add(this.label8);
			this.groupBox1.Controls.Add(this.label10);
			this.groupBox1.Controls.Add(this.label9);
			this.groupBox1.Location = new Point(167, 146);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new Size(186, 180);
			this.groupBox1.TabIndex = 24;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Trigger";
			this.label18.AutoSize = true;
			this.label18.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label18.Location = new Point(51, 164);
			this.label18.Name = "label18";
			this.label18.Size = new Size(46, 13);
			this.label18.TabIndex = 24;
			this.label18.Text = "(1 - 256)";
			this.label17.AutoSize = true;
			this.label17.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label17.Location = new Point(102, 144);
			this.label17.Name = "label17";
			this.label17.Size = new Size(46, 15);
			this.label17.TabIndex = 23;
			this.label17.Text = "times.";
			this.label15.AutoSize = true;
			this.label15.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label15.Location = new Point(6, 16);
			this.label15.Name = "label15";
			this.label15.Size = new Size(91, 15);
			this.label15.TabIndex = 20;
			this.label15.Text = "Trigger when";
			this.textBox1.Location = new Point(53, 143);
			this.textBox1.Name = "textBox1";
			this.textBox1.Size = new Size(43, 20);
			this.textBox1.TabIndex = 22;
			this.textBox1.Text = "1";
			this.textBox1.TextAlign = HorizontalAlignment.Center;
			this.textBox1.Leave += new EventHandler(this.TextBox1_Leave);
			this.label5.AutoSize = true;
			this.label5.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label5.Location = new Point(6, 48);
			this.label5.Name = "label5";
			this.label5.Size = new Size(45, 15);
			this.label5.TabIndex = 7;
			this.label5.Text = "Ch 1 = ";
			this.label16.AutoSize = true;
			this.label16.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label16.Location = new Point(6, 144);
			this.label16.Name = "label16";
			this.label16.Size = new Size(49, 15);
			this.label16.TabIndex = 21;
			this.label16.Text = "occurs";
			this.label6.AutoSize = true;
			this.label6.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label6.Location = new Point(6, 79);
			this.label6.Name = "label6";
			this.label6.Size = new Size(45, 15);
			this.label6.TabIndex = 8;
			this.label6.Text = "Ch 2 = ";
			this.label7.AutoSize = true;
			this.label7.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label7.Location = new Point(6, 111);
			this.label7.Name = "label7";
			this.label7.Size = new Size(45, 15);
			this.label7.TabIndex = 9;
			this.label7.Text = "Ch 3 = ";
			this.label14.AutoSize = true;
			this.label14.Location = new Point(102, 63);
			this.label14.Name = "label14";
			this.label14.Size = new Size(73, 13);
			this.label14.TabIndex = 19;
			this.label14.Text = "1 - Logic High";
			this.comboBoxCh1Trig.FormattingEnabled = true;
			this.comboBoxCh1Trig.Items.AddRange(new object[]
			{
				"*",
				"1",
				"0",
				"/",
				"\\"
			});
			this.comboBoxCh1Trig.Location = new Point(53, 45);
			this.comboBoxCh1Trig.Name = "comboBoxCh1Trig";
			this.comboBoxCh1Trig.Size = new Size(43, 21);
			this.comboBoxCh1Trig.TabIndex = 10;
			this.comboBoxCh1Trig.SelectedIndexChanged += new EventHandler(this.ComboBoxCh1Trig_SelectedIndexChanged);
			this.label13.AutoSize = true;
			this.label13.Location = new Point(102, 81);
			this.label13.Name = "label13";
			this.label13.Size = new Size(71, 13);
			this.label13.TabIndex = 18;
			this.label13.Text = "0 - Logic Low";
			this.comboBoxCh2Trig.FormattingEnabled = true;
			this.comboBoxCh2Trig.Items.AddRange(new object[]
			{
				"*",
				"1",
				"0",
				"/",
				"\\"
			});
			this.comboBoxCh2Trig.Location = new Point(53, 76);
			this.comboBoxCh2Trig.Name = "comboBoxCh2Trig";
			this.comboBoxCh2Trig.Size = new Size(43, 21);
			this.comboBoxCh2Trig.TabIndex = 11;
			this.comboBoxCh2Trig.SelectedIndexChanged += new EventHandler(this.ComboBoxCh2Trig_SelectedIndexChanged);
			this.label12.AutoSize = true;
			this.label12.Location = new Point(102, 99);
			this.label12.Name = "label12";
			this.label12.Size = new Size(78, 13);
			this.label12.TabIndex = 17;
			this.label12.Text = "/ - Rising Edge";
			this.comboBoxCh3Trig.FormattingEnabled = true;
			this.comboBoxCh3Trig.Items.AddRange(new object[]
			{
				"*",
				"1",
				"0",
				"/",
				"\\"
			});
			this.comboBoxCh3Trig.Location = new Point(53, 108);
			this.comboBoxCh3Trig.Name = "comboBoxCh3Trig";
			this.comboBoxCh3Trig.Size = new Size(43, 21);
			this.comboBoxCh3Trig.TabIndex = 12;
			this.comboBoxCh3Trig.SelectedIndexChanged += new EventHandler(this.ComboBoxCh3Trig_SelectedIndexChanged);
			this.label11.AutoSize = true;
			this.label11.Location = new Point(102, 117);
			this.label11.Name = "label11";
			this.label11.Size = new Size(79, 13);
			this.label11.TabIndex = 16;
			this.label11.Text = "\\ - Falling Edge";
			this.label8.AutoSize = true;
			this.label8.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label8.Location = new Point(22, 63);
			this.label8.Name = "label8";
			this.label8.Size = new Size(25, 13);
			this.label8.TabIndex = 13;
			this.label8.Text = "and";
			this.label10.AutoSize = true;
			this.label10.Location = new Point(102, 45);
			this.label10.Name = "label10";
			this.label10.Size = new Size(70, 13);
			this.label10.TabIndex = 15;
			this.label10.Text = "* - Don't Care";
			this.label9.AutoSize = true;
			this.label9.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label9.Location = new Point(22, 94);
			this.label9.Name = "label9";
			this.label9.Size = new Size(25, 13);
			this.label9.TabIndex = 14;
			this.label9.Text = "and";
			this.groupBoxZoom.Controls.Add(this.radioButton4x);
			this.groupBoxZoom.Controls.Add(this.radioButtonZoom05);
			this.groupBoxZoom.Controls.Add(this.radioButton2x);
			this.groupBoxZoom.Controls.Add(this.radioButtonZoom1x);
			this.groupBoxZoom.Location = new Point(542, 13);
			this.groupBoxZoom.Name = "groupBoxZoom";
			this.groupBoxZoom.Size = new Size(68, 100);
			this.groupBoxZoom.TabIndex = 6;
			this.groupBoxZoom.TabStop = false;
			this.groupBoxZoom.Text = "Zoom";
			this.radioButton4x.AutoSize = true;
			this.radioButton4x.Location = new Point(9, 73);
			this.radioButton4x.Name = "radioButton4x";
			this.radioButton4x.Size = new Size(36, 17);
			this.radioButton4x.TabIndex = 10;
			this.radioButton4x.Text = "4x";
			this.radioButton4x.UseVisualStyleBackColor = true;
			this.radioButton4x.Click += new EventHandler(this.RadioButtonZoom05_Click);
			this.radioButtonZoom05.AutoSize = true;
			this.radioButtonZoom05.Location = new Point(9, 19);
			this.radioButtonZoom05.Name = "radioButtonZoom05";
			this.radioButtonZoom05.Size = new Size(45, 17);
			this.radioButtonZoom05.TabIndex = 7;
			this.radioButtonZoom05.Text = "0.5x";
			this.radioButtonZoom05.UseVisualStyleBackColor = true;
			this.radioButtonZoom05.Click += new EventHandler(this.RadioButtonZoom05_Click);
			this.radioButton2x.AutoSize = true;
			this.radioButton2x.Location = new Point(9, 55);
			this.radioButton2x.Name = "radioButton2x";
			this.radioButton2x.Size = new Size(36, 17);
			this.radioButton2x.TabIndex = 9;
			this.radioButton2x.Text = "2x";
			this.radioButton2x.UseVisualStyleBackColor = true;
			this.radioButton2x.Click += new EventHandler(this.RadioButtonZoom05_Click);
			this.radioButtonZoom1x.AutoSize = true;
			this.radioButtonZoom1x.Checked = true;
			this.radioButtonZoom1x.Location = new Point(9, 37);
			this.radioButtonZoom1x.Name = "radioButtonZoom1x";
			this.radioButtonZoom1x.Size = new Size(36, 17);
			this.radioButtonZoom1x.TabIndex = 8;
			this.radioButtonZoom1x.TabStop = true;
			this.radioButtonZoom1x.Text = "1x";
			this.radioButtonZoom1x.UseVisualStyleBackColor = true;
			this.radioButtonZoom1x.Click += new EventHandler(this.RadioButtonZoom05_Click);
			this.labelTimeScale.AutoSize = true;
			this.labelTimeScale.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelTimeScale.Location = new Point(33, 0);
			this.labelTimeScale.Name = "labelTimeScale";
			this.labelTimeScale.Size = new Size(70, 15);
			this.labelTimeScale.TabIndex = 5;
			this.labelTimeScale.Text = "50us / Div";
			this.label4.AutoSize = true;
			this.label4.Location = new Point(1, 95);
			this.label4.Name = "label4";
			this.label4.Size = new Size(29, 13);
			this.label4.TabIndex = 4;
			this.label4.Text = "Ch.3";
			this.label3.AutoSize = true;
			this.label3.Location = new Point(1, 65);
			this.label3.Name = "label3";
			this.label3.Size = new Size(29, 13);
			this.label3.TabIndex = 3;
			this.label3.Text = "Ch.2";
			this.label1.AutoSize = true;
			this.label1.Location = new Point(1, 35);
			this.label1.Name = "label1";
			this.label1.Size = new Size(29, 13);
			this.label1.TabIndex = 2;
			this.label1.Text = "Ch.1";
			this.panelDisplay.AutoScroll = true;
			this.panelDisplay.BorderStyle = BorderStyle.Fixed3D;
			this.panelDisplay.Controls.Add(this.pictureBoxDisplay);
			this.panelDisplay.Location = new Point(36, 20);
			this.panelDisplay.Name = "panelDisplay";
			this.panelDisplay.Size = new Size(500, 122);
			this.panelDisplay.TabIndex = 1;
			this.pictureBoxDisplay.Location = new Point(0, 0);
			this.pictureBoxDisplay.Name = "pictureBoxDisplay";
			this.pictureBoxDisplay.Size = new Size(1024, 100);
			this.pictureBoxDisplay.TabIndex = 0;
			this.pictureBoxDisplay.TabStop = false;
			this.pictureBoxDisplay.MouseDown += new MouseEventHandler(this.PictureBoxDisplay_MouseDown);
			this.buttonExit.Location = new Point(508, 371);
			this.buttonExit.Name = "buttonExit";
			this.buttonExit.Size = new Size(116, 23);
			this.buttonExit.TabIndex = 27;
			this.buttonExit.Text = "Exit Logic Tool";
			this.buttonExit.UseVisualStyleBackColor = true;
			this.buttonExit.Click += new EventHandler(this.ButtonExit_Click);
			this.buttonHelp.Location = new Point(12, 371);
			this.buttonHelp.Name = "buttonHelp";
			this.buttonHelp.Size = new Size(56, 23);
			this.buttonHelp.TabIndex = 32;
			this.buttonHelp.Text = "Help";
			this.buttonHelp.UseVisualStyleBackColor = true;
			this.buttonHelp.Click += new EventHandler(this.ButtonHelp_Click);
			this.timerRun.Interval = 250;
			this.timerRun.Tick += new EventHandler(this.TimerRun_Tick);
			this.saveFileDialogDisplay.DefaultExt = "bmp";
			this.saveFileDialogDisplay.Filter = "Bitmap(.bmp)|*.bmp";
			this.saveFileDialogDisplay.InitialDirectory = "c:\\";
			this.saveFileDialogDisplay.Title = "Save Logic Analyzer Display";
			this.panelLogicIO.Controls.Add(this.checkBoxIOEnable);
			this.panelLogicIO.Controls.Add(this.labelOut6Click);
			this.panelLogicIO.Controls.Add(this.labelOut5Click);
			this.panelLogicIO.Controls.Add(this.labelOut4Click);
			this.panelLogicIO.Controls.Add(this.labelOut1Click);
			this.panelLogicIO.Controls.Add(this.textBoxPin6Out);
			this.panelLogicIO.Controls.Add(this.textBoxPin6In);
			this.panelLogicIO.Controls.Add(this.textBoxPin5Out);
			this.panelLogicIO.Controls.Add(this.textBoxPin5In);
			this.panelLogicIO.Controls.Add(this.textBoxPin4Out);
			this.panelLogicIO.Controls.Add(this.textBoxPin1Out);
			this.panelLogicIO.Controls.Add(this.label34);
			this.panelLogicIO.Controls.Add(this.label33);
			this.panelLogicIO.Controls.Add(this.textBoxPin4In);
			this.panelLogicIO.Controls.Add(this.label32);
			this.panelLogicIO.Controls.Add(this.label31);
			this.panelLogicIO.Controls.Add(this.panel4);
			this.panelLogicIO.Controls.Add(this.panel3);
			this.panelLogicIO.Controls.Add(this.panel1);
			this.panelLogicIO.Controls.Add(this.label30);
			this.panelLogicIO.Controls.Add(this.label29);
			this.panelLogicIO.Controls.Add(this.label28);
			this.panelLogicIO.Controls.Add(this.label27);
			this.panelLogicIO.Controls.Add(this.label26);
			this.panelLogicIO.Controls.Add(this.label20);
			this.panelLogicIO.Controls.Add(this.pictureBox2);
			this.panelLogicIO.Location = new Point(12, 39);
			this.panelLogicIO.Name = "panelLogicIO";
			this.panelLogicIO.Size = new Size(610, 326);
			this.panelLogicIO.TabIndex = 33;
			this.checkBoxIOEnable.Appearance = Appearance.Button;
			this.checkBoxIOEnable.Location = new Point(515, 277);
			this.checkBoxIOEnable.Name = "checkBoxIOEnable";
			this.checkBoxIOEnable.Size = new Size(78, 34);
			this.checkBoxIOEnable.TabIndex = 52;
			this.checkBoxIOEnable.Text = "Enable IO";
			this.checkBoxIOEnable.TextAlign = ContentAlignment.MiddleCenter;
			this.checkBoxIOEnable.UseVisualStyleBackColor = true;
			this.checkBoxIOEnable.CheckedChanged += new EventHandler(this.CheckBoxIOEnable_CheckedChanged);
			this.labelOut6Click.AutoSize = true;
			this.labelOut6Click.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelOut6Click.ForeColor = SystemColors.ControlDarkDark;
			this.labelOut6Click.Location = new Point(419, 243);
			this.labelOut6Click.Name = "labelOut6Click";
			this.labelOut6Click.Size = new Size(178, 13);
			this.labelOut6Click.TabIndex = 51;
			this.labelOut6Click.Text = "<- Click Output box or press <F> key";
			this.labelOut5Click.AutoSize = true;
			this.labelOut5Click.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelOut5Click.ForeColor = SystemColors.ControlDarkDark;
			this.labelOut5Click.Location = new Point(419, 177);
			this.labelOut5Click.Name = "labelOut5Click";
			this.labelOut5Click.Size = new Size(180, 13);
			this.labelOut5Click.TabIndex = 50;
			this.labelOut5Click.Text = "<- Click Output box or press <D> key";
			this.labelOut4Click.AutoSize = true;
			this.labelOut4Click.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelOut4Click.ForeColor = SystemColors.ControlDarkDark;
			this.labelOut4Click.Location = new Point(419, 111);
			this.labelOut4Click.Name = "labelOut4Click";
			this.labelOut4Click.Size = new Size(179, 13);
			this.labelOut4Click.TabIndex = 49;
			this.labelOut4Click.Text = "<- Click Output box or press <S> key";
			this.labelOut1Click.AutoSize = true;
			this.labelOut1Click.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelOut1Click.ForeColor = SystemColors.ControlDarkDark;
			this.labelOut1Click.Location = new Point(419, 45);
			this.labelOut1Click.Name = "labelOut1Click";
			this.labelOut1Click.Size = new Size(179, 13);
			this.labelOut1Click.TabIndex = 48;
			this.labelOut1Click.Text = "<- Click Output box or press <A> key";
			this.textBoxPin6Out.BackColor = SystemColors.Control;
			this.textBoxPin6Out.Cursor = Cursors.Hand;
			this.textBoxPin6Out.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin6Out.ForeColor = SystemColors.Window;
			this.textBoxPin6Out.Location = new Point(350, 237);
			this.textBoxPin6Out.Name = "textBoxPin6Out";
			this.textBoxPin6Out.ReadOnly = true;
			this.textBoxPin6Out.Size = new Size(30, 29);
			this.textBoxPin6Out.TabIndex = 47;
			this.textBoxPin6Out.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin6Out.Click += new EventHandler(this.TextBoxPin6Out_Click);
			this.textBoxPin6In.BackColor = SystemColors.Control;
			this.textBoxPin6In.Cursor = Cursors.Default;
			this.textBoxPin6In.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin6In.ForeColor = SystemColors.Window;
			this.textBoxPin6In.Location = new Point(266, 239);
			this.textBoxPin6In.Name = "textBoxPin6In";
			this.textBoxPin6In.ReadOnly = true;
			this.textBoxPin6In.Size = new Size(30, 29);
			this.textBoxPin6In.TabIndex = 46;
			this.textBoxPin6In.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin5Out.BackColor = Color.Red;
			this.textBoxPin5Out.Cursor = Cursors.Hand;
			this.textBoxPin5Out.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin5Out.ForeColor = SystemColors.Window;
			this.textBoxPin5Out.Location = new Point(350, 173);
			this.textBoxPin5Out.Name = "textBoxPin5Out";
			this.textBoxPin5Out.ReadOnly = true;
			this.textBoxPin5Out.Size = new Size(30, 29);
			this.textBoxPin5Out.TabIndex = 45;
			this.textBoxPin5Out.Text = "1";
			this.textBoxPin5Out.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin5Out.Click += new EventHandler(this.TextBoxPin5Out_Click);
			this.textBoxPin5In.BackColor = Color.DodgerBlue;
			this.textBoxPin5In.Cursor = Cursors.Default;
			this.textBoxPin5In.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin5In.ForeColor = SystemColors.Window;
			this.textBoxPin5In.Location = new Point(266, 173);
			this.textBoxPin5In.Name = "textBoxPin5In";
			this.textBoxPin5In.ReadOnly = true;
			this.textBoxPin5In.Size = new Size(30, 29);
			this.textBoxPin5In.TabIndex = 44;
			this.textBoxPin5In.Text = "1";
			this.textBoxPin5In.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin4Out.BackColor = Color.DarkRed;
			this.textBoxPin4Out.Cursor = Cursors.Hand;
			this.textBoxPin4Out.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin4Out.ForeColor = SystemColors.Window;
			this.textBoxPin4Out.Location = new Point(350, 107);
			this.textBoxPin4Out.Name = "textBoxPin4Out";
			this.textBoxPin4Out.ReadOnly = true;
			this.textBoxPin4Out.Size = new Size(30, 29);
			this.textBoxPin4Out.TabIndex = 43;
			this.textBoxPin4Out.Text = "0";
			this.textBoxPin4Out.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin4Out.Click += new EventHandler(this.TextBoxPin4Out_Click);
			this.textBoxPin1Out.BackColor = Color.DarkRed;
			this.textBoxPin1Out.Cursor = Cursors.Hand;
			this.textBoxPin1Out.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin1Out.ForeColor = SystemColors.Window;
			this.textBoxPin1Out.Location = new Point(350, 39);
			this.textBoxPin1Out.Name = "textBoxPin1Out";
			this.textBoxPin1Out.ReadOnly = true;
			this.textBoxPin1Out.Size = new Size(30, 29);
			this.textBoxPin1Out.TabIndex = 42;
			this.textBoxPin1Out.Text = "0";
			this.textBoxPin1Out.TextAlign = HorizontalAlignment.Center;
			this.textBoxPin1Out.Click += new EventHandler(this.TextBoxPin1Out_Click);
			this.label34.AutoSize = true;
			this.label34.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold | FontStyle.Underline, GraphicsUnit.Point, 0);
			this.label34.Location = new Point(260, 13);
			this.label34.Name = "label34";
			this.label34.Size = new Size(49, 16);
			this.label34.TabIndex = 41;
			this.label34.Text = "Inputs";
			this.label33.AutoSize = true;
			this.label33.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold | FontStyle.Underline, GraphicsUnit.Point, 0);
			this.label33.Location = new Point(338, 13);
			this.label33.Name = "label33";
			this.label33.Size = new Size(60, 16);
			this.label33.TabIndex = 40;
			this.label33.Text = "Outputs";
			this.textBoxPin4In.BackColor = Color.DarkBlue;
			this.textBoxPin4In.Cursor = Cursors.Default;
			this.textBoxPin4In.Font = new Font("Microsoft Sans Serif", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.textBoxPin4In.ForeColor = SystemColors.Window;
			this.textBoxPin4In.Location = new Point(266, 107);
			this.textBoxPin4In.Name = "textBoxPin4In";
			this.textBoxPin4In.ReadOnly = true;
			this.textBoxPin4In.Size = new Size(30, 29);
			this.textBoxPin4In.TabIndex = 38;
			this.textBoxPin4In.Text = "0";
			this.textBoxPin4In.TextAlign = HorizontalAlignment.Center;
			this.label32.AutoSize = true;
			this.label32.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label32.ForeColor = SystemColors.ControlDarkDark;
			this.label32.Location = new Point(108, 197);
			this.label32.Name = "label32";
			this.label32.Size = new Size(53, 26);
			this.label32.TabIndex = 37;
			this.label32.Text = "4.7k Ohm\r\npulldown";
			this.label31.AutoSize = true;
			this.label31.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label31.ForeColor = SystemColors.ControlDarkDark;
			this.label31.Location = new Point(108, 131);
			this.label31.Name = "label31";
			this.label31.Size = new Size(53, 26);
			this.label31.TabIndex = 36;
			this.label31.Text = "4.7k Ohm\r\npulldown";
			this.panel4.Controls.Add(this.radioButtonPin6In);
			this.panel4.Controls.Add(this.radioButtonPin6Out);
			this.panel4.Location = new Point(170, 233);
			this.panel4.Name = "panel4";
			this.panel4.Size = new Size(60, 45);
			this.panel4.TabIndex = 35;
			this.radioButtonPin6In.AutoSize = true;
			this.radioButtonPin6In.Checked = true;
			this.radioButtonPin6In.Enabled = false;
			this.radioButtonPin6In.Location = new Point(3, 21);
			this.radioButtonPin6In.Name = "radioButtonPin6In";
			this.radioButtonPin6In.Size = new Size(49, 17);
			this.radioButtonPin6In.TabIndex = 1;
			this.radioButtonPin6In.TabStop = true;
			this.radioButtonPin6In.Text = "Input";
			this.radioButtonPin6In.UseVisualStyleBackColor = true;
			this.radioButtonPin6Out.AutoSize = true;
			this.radioButtonPin6Out.Enabled = false;
			this.radioButtonPin6Out.Location = new Point(3, 3);
			this.radioButtonPin6Out.Name = "radioButtonPin6Out";
			this.radioButtonPin6Out.Size = new Size(57, 17);
			this.radioButtonPin6Out.TabIndex = 0;
			this.radioButtonPin6Out.Text = "Output";
			this.radioButtonPin6Out.UseVisualStyleBackColor = true;
			this.radioButtonPin6Out.CheckedChanged += new EventHandler(this.RadioButtonPin6Out_CheckedChanged);
			this.panel3.Controls.Add(this.radioButtonPin5In);
			this.panel3.Controls.Add(this.radioButtonPin5Out);
			this.panel3.Location = new Point(170, 167);
			this.panel3.Name = "panel3";
			this.panel3.Size = new Size(60, 45);
			this.panel3.TabIndex = 34;
			this.radioButtonPin5In.AutoSize = true;
			this.radioButtonPin5In.Checked = true;
			this.radioButtonPin5In.Enabled = false;
			this.radioButtonPin5In.Location = new Point(3, 21);
			this.radioButtonPin5In.Name = "radioButtonPin5In";
			this.radioButtonPin5In.Size = new Size(49, 17);
			this.radioButtonPin5In.TabIndex = 1;
			this.radioButtonPin5In.TabStop = true;
			this.radioButtonPin5In.Text = "Input";
			this.radioButtonPin5In.UseVisualStyleBackColor = true;
			this.radioButtonPin5Out.AutoSize = true;
			this.radioButtonPin5Out.Enabled = false;
			this.radioButtonPin5Out.Location = new Point(3, 3);
			this.radioButtonPin5Out.Name = "radioButtonPin5Out";
			this.radioButtonPin5Out.Size = new Size(57, 17);
			this.radioButtonPin5Out.TabIndex = 0;
			this.radioButtonPin5Out.Text = "Output";
			this.radioButtonPin5Out.UseVisualStyleBackColor = true;
			this.radioButtonPin5Out.CheckedChanged += new EventHandler(this.RadioButtonPin5Out_CheckedChanged);
			this.panel1.Controls.Add(this.radioButtonPin4In);
			this.panel1.Controls.Add(this.radioButtonPin4Out);
			this.panel1.Location = new Point(170, 101);
			this.panel1.Name = "panel1";
			this.panel1.Size = new Size(60, 45);
			this.panel1.TabIndex = 33;
			this.radioButtonPin4In.AutoSize = true;
			this.radioButtonPin4In.Checked = true;
			this.radioButtonPin4In.Enabled = false;
			this.radioButtonPin4In.Location = new Point(3, 21);
			this.radioButtonPin4In.Name = "radioButtonPin4In";
			this.radioButtonPin4In.Size = new Size(49, 17);
			this.radioButtonPin4In.TabIndex = 1;
			this.radioButtonPin4In.TabStop = true;
			this.radioButtonPin4In.Text = "Input";
			this.radioButtonPin4In.UseVisualStyleBackColor = true;
			this.radioButtonPin4Out.AutoSize = true;
			this.radioButtonPin4Out.Enabled = false;
			this.radioButtonPin4Out.Location = new Point(3, 3);
			this.radioButtonPin4Out.Name = "radioButtonPin4Out";
			this.radioButtonPin4Out.Size = new Size(57, 17);
			this.radioButtonPin4Out.TabIndex = 0;
			this.radioButtonPin4Out.Text = "Output";
			this.radioButtonPin4Out.UseVisualStyleBackColor = true;
			this.radioButtonPin4Out.CheckedChanged += new EventHandler(this.RadioButtonPin4Out_CheckedChanged);
			this.label30.AutoSize = true;
			this.label30.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Italic, GraphicsUnit.Point, 0);
			this.label30.Location = new Point(167, 50);
			this.label30.Name = "label30";
			this.label30.Size = new Size(63, 13);
			this.label30.TabIndex = 32;
			this.label30.Text = "Output Only";
			this.label29.AutoSize = true;
			this.label29.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label29.Location = new Point(106, 243);
			this.label29.Name = "label29";
			this.label29.Size = new Size(49, 20);
			this.label29.TabIndex = 31;
			this.label29.Text = "Pin 6";
			this.label28.AutoSize = true;
			this.label28.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label28.Location = new Point(106, 177);
			this.label28.Name = "label28";
			this.label28.Size = new Size(49, 20);
			this.label28.TabIndex = 30;
			this.label28.Text = "Pin 5";
			this.label27.AutoSize = true;
			this.label27.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label27.Location = new Point(106, 111);
			this.label27.Name = "label27";
			this.label27.Size = new Size(49, 20);
			this.label27.TabIndex = 29;
			this.label27.Text = "Pin 4";
			this.label26.AutoSize = true;
			this.label26.Location = new Point(-3, 300);
			this.label26.Name = "label26";
			this.label26.Size = new Size(356, 26);
			this.label26.TabIndex = 28;
			this.label26.Text = "PICkit 2 VDD pin MUST have a valid voltage (either sourced from PICkit 2\r\nor the target) or pins 4, 5, && 6 will not function.";
			this.label20.AutoSize = true;
			this.label20.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label20.Location = new Point(106, 45);
			this.label20.Name = "label20";
			this.label20.Size = new Size(49, 20);
			this.label20.TabIndex = 27;
			this.label20.Text = "Pin 1";
			this.pictureBox2.Image = (Image)resources.GetObject("pictureBox2.Image");
			this.pictureBox2.Location = new Point(0, 106);
			this.pictureBox2.Name = "pictureBox2";
			this.pictureBox2.Size = new Size(78, 116);
			this.pictureBox2.TabIndex = 26;
			this.pictureBox2.TabStop = false;
			this.timerIO.Tick += new EventHandler(this.TimerIO_Tick);
			this.checkBoxVDD.AutoSize = true;
			this.checkBoxVDD.Location = new Point(12, 16);
			this.checkBoxVDD.Name = "checkBoxVDD";
			this.checkBoxVDD.Size = new Size(66, 17);
			this.checkBoxVDD.TabIndex = 34;
			this.checkBoxVDD.Text = "VDD On";
			this.checkBoxVDD.UseVisualStyleBackColor = true;
			this.checkBoxVDD.Click += new EventHandler(this.CheckBoxVdd_Click);
			base.AutoScaleDimensions = new SizeF(96f, 96f);
			base.AutoScaleMode = AutoScaleMode.Dpi;
			base.ClientSize = new Size(634, 401);
			base.Controls.Add(this.checkBoxVDD);
			base.Controls.Add(this.panelLogicIO);
			base.Controls.Add(this.buttonHelp);
			base.Controls.Add(this.buttonExit);
			base.Controls.Add(this.panelAnalyzer);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.panel2);
			base.FormBorderStyle = FormBorderStyle.FixedSingle;
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "DialogLogic";
			base.StartPosition = FormStartPosition.CenterScreen;
			this.Text = "PICkit 2 Logic Tool";
			this.panel2.ResumeLayout(false);
			this.panelAnalyzer.ResumeLayout(false);
			this.panelAnalyzer.PerformLayout();
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			((ISupportInitialize)this.pictureBox1).EndInit();
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBoxZoom.ResumeLayout(false);
			this.groupBoxZoom.PerformLayout();
			this.panelDisplay.ResumeLayout(false);
			((ISupportInitialize)this.pictureBoxDisplay).EndInit();
			this.panelLogicIO.ResumeLayout(false);
			this.panelLogicIO.PerformLayout();
			this.panel4.ResumeLayout(false);
			this.panel4.PerformLayout();
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			this.panel1.ResumeLayout(false);
			this.panel1.PerformLayout();
			((ISupportInitialize)this.pictureBox2).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

        private IContainer components;
        private Label label2;
        private Panel panel2;
        private RadioButton radioButtonAnalyzer;
        private RadioButton radioButtonLogicIO;
        private Panel panelAnalyzer;
        private PictureBox pictureBoxDisplay;
        private Panel panelDisplay;
        private Label label4;
        private Label label3;
        private Label label1;
        private GroupBox groupBoxZoom;
        private Label labelTimeScale;
        private RadioButton radioButton4x;
        private RadioButton radioButtonZoom05;
        private RadioButton radioButton2x;
        private RadioButton radioButtonZoom1x;
        private Label label8;
        private ComboBox comboBoxCh3Trig;
        private ComboBox comboBoxCh2Trig;
        private ComboBox comboBoxCh1Trig;
        private Label label7;
        private Label label6;
        private Label label5;
        private Label label9;
        private Label label14;
        private Label label13;
        private Label label12;
        private Label label11;
        private Label label10;
        private Label label17;
        private TextBox textBox1;
        private Label label16;
        private Label label15;
        private Button buttonExit;
        private GroupBox groupBox2;
        private PictureBox pictureBox1;
        private GroupBox groupBox1;
        private Button buttonRun;
        private Label label18;
        private ComboBox comboBoxSampleRate;
        private Label label19;
        private RadioButton radioButtonTrigStart;
        private Label label21;
        private Label labelAliasFreq;
        private RadioButton radioButtonTrigDly3;
        private RadioButton radioButtonTrigDly2;
        private RadioButton radioButtonTrigDly1;
        private RadioButton radioButtonTrigEnd;
        private RadioButton radioButtonTrigMid;
        private Label label22;
        private Label label23;
        private Label label24;
        private Label label25;
        private Label labelCursor1Val;
        private CheckBox checkBoxCursors;
        private Label labelCursor1;
        private Label labelCursor2Val;
        private Label labelCursor2;
        private Label labelCursorDelta;
        private Label labelCursorDeltaVal;
        private Button buttonHelp;
        private Timer timerRun;
        private Button buttonSave;
        private SaveFileDialog saveFileDialogDisplay;
        private Panel panelLogicIO;
        private PictureBox pictureBox2;
        private Label label20;
        private Label label29;
        private Label label28;
        private Label label27;
        private Label label26;
        private Panel panel4;
        private RadioButton radioButtonPin6In;
        private RadioButton radioButtonPin6Out;
        private Panel panel3;
        private RadioButton radioButtonPin5In;
        private RadioButton radioButtonPin5Out;
        private Panel panel1;
        private RadioButton radioButtonPin4In;
        private RadioButton radioButtonPin4Out;
        private Label label30;
        private TextBox textBoxPin4In;
        private Label label32;
        private Label label31;
        private TextBox textBoxPin4Out;
        private TextBox textBoxPin1Out;
        private Label label34;
        private Label label33;
        private TextBox textBoxPin5In;
        private TextBox textBoxPin5Out;
        private TextBox textBoxPin6Out;
        private TextBox textBoxPin6In;
        private CheckBox checkBoxIOEnable;
        private Label labelOut6Click;
        private Label labelOut5Click;
        private Label labelOut4Click;
        private Label labelOut1Click;
        private Timer timerIO;
        private CheckBox checkBoxVDD;
    }
}
