using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PICkit2V3
{
	public partial class DialogCalibrate : Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			ComponentResourceManager resources = new ComponentResourceManager(typeof(PICkit2V3.DialogCalibrate));
			this.panelIntro = new Panel();
			this.label2 = new Label();
			this.buttonClearUnitID = new Button();
			this.buttonClearCal = new Button();
			this.label1 = new Label();
			this.buttonBack = new Button();
			this.buttonNext = new Button();
			this.buttonCancel = new Button();
			this.panelSetup = new Panel();
			this.label11 = new Label();
			this.label6 = new Label();
			this.label5 = new Label();
			this.label4 = new Label();
			this.pictureBox1 = new PictureBox();
			this.label3 = new Label();
			this.panelCal = new Panel();
			this.labelBadCal = new Label();
			this.labelGoodCal = new Label();
			this.buttonCalibrate = new Button();
			this.label8 = new Label();
			this.label7 = new Label();
			this.textBoxVDD = new TextBox();
			this.label9 = new Label();
			this.pictureBox2 = new PictureBox();
			this.label10 = new Label();
			this.panelUnitID = new Panel();
			this.labelAssignedID = new Label();
			this.buttonSetUnitID = new Button();
			this.textBoxUnitID = new TextBox();
			this.label12 = new Label();
			this.label15 = new Label();
			this.label16 = new Label();
			this.panelIntro.SuspendLayout();
			this.panelSetup.SuspendLayout();
			((ISupportInitialize)this.pictureBox1).BeginInit();
			this.panelCal.SuspendLayout();
			((ISupportInitialize)this.pictureBox2).BeginInit();
			this.panelUnitID.SuspendLayout();
			base.SuspendLayout();
			this.panelIntro.Controls.Add(this.label2);
			this.panelIntro.Controls.Add(this.buttonClearUnitID);
			this.panelIntro.Controls.Add(this.buttonClearCal);
			this.panelIntro.Controls.Add(this.label1);
			this.panelIntro.Location = new Point(13, 12);
			this.panelIntro.Name = "panelIntro";
			this.panelIntro.Size = new Size(330, 236);
			this.panelIntro.TabIndex = 0;
			this.label2.AutoSize = true;
			this.label2.Location = new Point(0, 29);
			this.label2.Name = "label2";
			this.label2.Size = new Size(307, 169);
			this.label2.TabIndex = 3;
			this.label2.Text = resources.GetString("label2.Text");
			this.buttonClearUnitID.Enabled = false;
			this.buttonClearUnitID.Location = new Point(176, 205);
			this.buttonClearUnitID.Name = "buttonClearUnitID";
			this.buttonClearUnitID.Size = new Size(134, 22);
			this.buttonClearUnitID.TabIndex = 2;
			this.buttonClearUnitID.Text = "Clear Unit ID";
			this.buttonClearUnitID.UseVisualStyleBackColor = true;
			this.buttonClearUnitID.Click += new EventHandler(this.ButtonClearUnitID_Click);
			this.buttonClearCal.Enabled = false;
			this.buttonClearCal.Location = new Point(22, 205);
			this.buttonClearCal.Name = "buttonClearCal";
			this.buttonClearCal.Size = new Size(134, 22);
			this.buttonClearCal.TabIndex = 1;
			this.buttonClearCal.Text = "Clear Calibration";
			this.buttonClearCal.UseVisualStyleBackColor = true;
			this.buttonClearCal.Click += new EventHandler(this.ButtonClearCal_Click);
			this.label1.AutoSize = true;
			this.label1.Font = new Font("Arial", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label1.Location = new Point(63, 0);
			this.label1.Name = "label1";
			this.label1.Size = new Size(193, 19);
			this.label1.TabIndex = 0;
			this.label1.Text = "PICkit 2 VDD Calibration";
			this.buttonBack.Enabled = false;
			this.buttonBack.Location = new Point(90, 254);
			this.buttonBack.Name = "buttonBack";
			this.buttonBack.Size = new Size(80, 22);
			this.buttonBack.TabIndex = 1;
			this.buttonBack.Text = "< Back";
			this.buttonBack.UseVisualStyleBackColor = true;
			this.buttonBack.Click += new EventHandler(this.ButtonBack_Click);
			this.buttonNext.Location = new Point(177, 254);
			this.buttonNext.Name = "buttonNext";
			this.buttonNext.Size = new Size(80, 22);
			this.buttonNext.TabIndex = 2;
			this.buttonNext.Text = "Next >";
			this.buttonNext.UseVisualStyleBackColor = true;
			this.buttonNext.Click += new EventHandler(this.ButtonNext_Click);
			this.buttonCancel.Location = new Point(263, 254);
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.Size = new Size(80, 22);
			this.buttonCancel.TabIndex = 3;
			this.buttonCancel.Text = "Cancel";
			this.buttonCancel.UseVisualStyleBackColor = true;
			this.buttonCancel.Click += new EventHandler(this.ButtonCancel_Click);
			this.panelSetup.Controls.Add(this.label11);
			this.panelSetup.Controls.Add(this.label6);
			this.panelSetup.Controls.Add(this.label5);
			this.panelSetup.Controls.Add(this.label4);
			this.panelSetup.Controls.Add(this.pictureBox1);
			this.panelSetup.Controls.Add(this.label3);
			this.panelSetup.Location = new Point(13, 12);
			this.panelSetup.Name = "panelSetup";
			this.panelSetup.Size = new Size(330, 236);
			this.panelSetup.TabIndex = 4;
			this.panelSetup.Visible = false;
			this.label11.AutoSize = true;
			this.label11.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label11.ForeColor = Color.Red;
			this.label11.Location = new Point(4, 222);
			this.label11.Name = "label11";
			this.label11.Size = new Size(306, 15);
			this.label11.TabIndex = 6;
			this.label11.Text = "CAUTION: Clicking NEXT will erase existing calibration.";
			this.label6.AutoSize = true;
			this.label6.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label6.Location = new Point(4, 168);
			this.label6.Name = "label6";
			this.label6.Size = new Size(289, 45);
			this.label6.TabIndex = 5;
			this.label6.Text = "Step 3:\r\nClick NEXT and the PICkit 2 will apply approximately\r\n4 Volts to the VDD pin.";
			this.label5.AutoSize = true;
			this.label5.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label5.Location = new Point(102, 94);
			this.label5.Name = "label5";
			this.label5.Size = new Size(195, 60);
			this.label5.TabIndex = 4;
			this.label5.Text = "Step 2:\r\nConnect a voltage meter between\r\npin 2 (VDD) and pin 3 (GND) of the\r\nPICkit 2 ICSP connector.";
			this.label4.AutoSize = true;
			this.label4.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label4.Location = new Point(102, 22);
			this.label4.Name = "label4";
			this.label4.Size = new Size(186, 60);
			this.label4.TabIndex = 3;
			this.label4.Text = "Step 1:\r\nMake sure the PICkit 2 is not\r\nconnected to any device or circuit\r\nboard.";
			this.pictureBox1.Image = (Image)resources.GetObject("pictureBox1.Image");
			this.pictureBox1.Location = new Point(0, 22);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new Size(78, 116);
			this.pictureBox1.SizeMode = PictureBoxSizeMode.AutoSize;
			this.pictureBox1.TabIndex = 2;
			this.pictureBox1.TabStop = false;
			this.label3.AutoSize = true;
			this.label3.Font = new Font("Arial", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label3.Location = new Point(61, 0);
			this.label3.Name = "label3";
			this.label3.Size = new Size(193, 19);
			this.label3.TabIndex = 1;
			this.label3.Text = "PICkit 2 VDD Calibration";
			this.panelCal.Controls.Add(this.labelBadCal);
			this.panelCal.Controls.Add(this.labelGoodCal);
			this.panelCal.Controls.Add(this.buttonCalibrate);
			this.panelCal.Controls.Add(this.label8);
			this.panelCal.Controls.Add(this.label7);
			this.panelCal.Controls.Add(this.textBoxVDD);
			this.panelCal.Controls.Add(this.label9);
			this.panelCal.Controls.Add(this.pictureBox2);
			this.panelCal.Controls.Add(this.label10);
			this.panelCal.Location = new Point(13, 12);
			this.panelCal.Name = "panelCal";
			this.panelCal.Size = new Size(330, 236);
			this.panelCal.TabIndex = 6;
			this.panelCal.Visible = false;
			this.labelBadCal.AutoSize = true;
			this.labelBadCal.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelBadCal.ForeColor = Color.Red;
			this.labelBadCal.Location = new Point(3, 198);
			this.labelBadCal.Name = "labelBadCal";
			this.labelBadCal.Size = new Size(276, 30);
			this.labelBadCal.TabIndex = 9;
			this.labelBadCal.Text = "Could not fully calibrate the unit.  The USB voltage\r\nmay be too low to completely calibrate.";
			this.labelBadCal.Visible = false;
			this.labelGoodCal.AutoSize = true;
			this.labelGoodCal.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelGoodCal.ForeColor = Color.Blue;
			this.labelGoodCal.Location = new Point(3, 208);
			this.labelGoodCal.Name = "labelGoodCal";
			this.labelGoodCal.Size = new Size(170, 15);
			this.labelGoodCal.TabIndex = 8;
			this.labelGoodCal.Text = "CALIBRATION SUCCESSFUL!";
			this.labelGoodCal.Visible = false;
			this.buttonCalibrate.Location = new Point(6, 172);
			this.buttonCalibrate.Name = "buttonCalibrate";
			this.buttonCalibrate.Size = new Size(112, 22);
			this.buttonCalibrate.TabIndex = 7;
			this.buttonCalibrate.Text = "Calibrate";
			this.buttonCalibrate.UseVisualStyleBackColor = true;
			this.buttonCalibrate.Click += new EventHandler(this.ButtonCalibrate_Click);
			this.label8.AutoSize = true;
			this.label8.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label8.Location = new Point(3, 139);
			this.label8.Name = "label8";
			this.label8.Size = new Size(287, 30);
			this.label8.TabIndex = 6;
			this.label8.Text = "Step 5:\r\nClick the CALIBRATE button to calibrate the PICkit 2.";
			this.label7.AutoSize = true;
			this.label7.Location = new Point(164, 104);
			this.label7.Name = "label7";
			this.label7.Size = new Size(80, 13);
			this.label7.TabIndex = 5;
			this.label7.Text = "Volts Measured";
			this.textBoxVDD.Location = new Point(105, 102);
			this.textBoxVDD.Name = "textBoxVDD";
			this.textBoxVDD.Size = new Size(53, 20);
			this.textBoxVDD.TabIndex = 4;
			this.textBoxVDD.Text = "4.000";
			this.label9.AutoSize = true;
			this.label9.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label9.Location = new Point(102, 22);
			this.label9.Name = "label9";
			this.label9.Size = new Size(209, 60);
			this.label9.TabIndex = 3;
			this.label9.Text = "Step 4:\r\nEnter the actual voltage measured\r\non the volt meter in the box below, up\r\nto 3 decimal places.";
			this.pictureBox2.Image = (Image)resources.GetObject("pictureBox2.Image");
			this.pictureBox2.Location = new Point(0, 22);
			this.pictureBox2.Name = "pictureBox2";
			this.pictureBox2.Size = new Size(78, 116);
			this.pictureBox2.SizeMode = PictureBoxSizeMode.AutoSize;
			this.pictureBox2.TabIndex = 2;
			this.pictureBox2.TabStop = false;
			this.label10.AutoSize = true;
			this.label10.Font = new Font("Arial", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label10.Location = new Point(61, 0);
			this.label10.Name = "label10";
			this.label10.Size = new Size(193, 19);
			this.label10.TabIndex = 1;
			this.label10.Text = "PICkit 2 VDD Calibration";
			this.panelUnitID.Controls.Add(this.labelAssignedID);
			this.panelUnitID.Controls.Add(this.buttonSetUnitID);
			this.panelUnitID.Controls.Add(this.textBoxUnitID);
			this.panelUnitID.Controls.Add(this.label12);
			this.panelUnitID.Controls.Add(this.label15);
			this.panelUnitID.Controls.Add(this.label16);
			this.panelUnitID.Location = new Point(13, 12);
			this.panelUnitID.Name = "panelUnitID";
			this.panelUnitID.Size = new Size(330, 236);
			this.panelUnitID.TabIndex = 7;
			this.panelUnitID.Visible = false;
			this.labelAssignedID.AutoSize = true;
			this.labelAssignedID.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.labelAssignedID.ForeColor = Color.Blue;
			this.labelAssignedID.Location = new Point(58, 217);
			this.labelAssignedID.Name = "labelAssignedID";
			this.labelAssignedID.Size = new Size(179, 15);
			this.labelAssignedID.TabIndex = 7;
			this.labelAssignedID.Text = "Unit ID Assigned to this PICkit 2.";
			this.labelAssignedID.Visible = false;
			this.buttonSetUnitID.Location = new Point(186, 188);
			this.buttonSetUnitID.Name = "buttonSetUnitID";
			this.buttonSetUnitID.Size = new Size(106, 22);
			this.buttonSetUnitID.TabIndex = 6;
			this.buttonSetUnitID.Text = "Assign Unit ID";
			this.buttonSetUnitID.UseVisualStyleBackColor = true;
			this.buttonSetUnitID.Click += new EventHandler(this.ButtonSetUnitID_Click);
			this.textBoxUnitID.Location = new Point(26, 190);
			this.textBoxUnitID.Name = "textBoxUnitID";
			this.textBoxUnitID.Size = new Size(134, 20);
			this.textBoxUnitID.TabIndex = 5;
			this.textBoxUnitID.Text = "AAAAAAAAAAAAAA";
			this.textBoxUnitID.TextChanged += new EventHandler(this.TextBoxUnitID_TextChanged);
			this.label12.AutoSize = true;
			this.label12.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label12.Location = new Point(118, 18);
			this.label12.Name = "label12";
			this.label12.Size = new Size(76, 18);
			this.label12.TabIndex = 4;
			this.label12.Text = "(Optional)";
			this.label15.AutoSize = true;
			this.label15.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label15.Location = new Point(0, 48);
			this.label15.Name = "label15";
			this.label15.Size = new Size(308, 120);
			this.label15.TabIndex = 3;
			this.label15.Text = resources.GetString("label15.Text");
			this.label16.AutoSize = true;
			this.label16.Font = new Font("Arial", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.label16.Location = new Point(61, 0);
			this.label16.Name = "label16";
			this.label16.Size = new Size(190, 19);
			this.label16.TabIndex = 1;
			this.label16.Text = "Unit Identification Name";
			base.AutoScaleDimensions = new SizeF(96f, 96f);
			base.AutoScaleMode = AutoScaleMode.Dpi;
			base.ClientSize = new Size(354, 282);
			base.Controls.Add(this.panelUnitID);
			base.Controls.Add(this.panelCal);
			base.Controls.Add(this.panelSetup);
			base.Controls.Add(this.buttonCancel);
			base.Controls.Add(this.buttonNext);
			base.Controls.Add(this.buttonBack);
			base.Controls.Add(this.panelIntro);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "DialogCalibrate";
			base.StartPosition = FormStartPosition.CenterParent;
			this.Text = "DialogCalibrate";
			this.panelIntro.ResumeLayout(false);
			this.panelIntro.PerformLayout();
			this.panelSetup.ResumeLayout(false);
			this.panelSetup.PerformLayout();
			((ISupportInitialize)this.pictureBox1).EndInit();
			this.panelCal.ResumeLayout(false);
			this.panelCal.PerformLayout();
			((ISupportInitialize)this.pictureBox2).EndInit();
			this.panelUnitID.ResumeLayout(false);
			this.panelUnitID.PerformLayout();
			base.ResumeLayout(false);
		}

		private IContainer components;
		private Panel panelIntro;
		private Button buttonBack;
		private Button buttonNext;
		private Button buttonCancel;
		private Label label1;
		private Label label2;
		private Button buttonClearUnitID;
		private Button buttonClearCal;
		private Panel panelSetup;
		private PictureBox pictureBox1;
		private Label label3;
		private Label label5;
		private Label label4;
		private Label label6;
		private Panel panelCal;
		private Label label9;
		private PictureBox pictureBox2;
		private Label label10;
		private TextBox textBoxVDD;
		private Label label7;
		private Label labelBadCal;
		private Label labelGoodCal;
		private Button buttonCalibrate;
		private Label label8;
		private Label label11;
		private Panel panelUnitID;
		private Label label12;
		private Label label15;
		private Label label16;
		private Button buttonSetUnitID;
		private TextBox textBoxUnitID;
		private Label labelAssignedID;
	}
}
