using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace PICkit2V3
{
	public partial class FormTestMemory : Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			DataGridViewCellStyle dataGridViewCellStyle = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
			this.dataGridTestMemory = new DataGridView();
			this.label1 = new Label();
			this.textBoxTestMemSize = new TextBox();
			this.labelTestMemSize8 = new Label();
			this.label11 = new Label();
			this.checkBoxTestMemImportExport = new CheckBox();
			this.label2 = new Label();
			this.label3 = new Label();
			this.labelBLConfig = new Label();
			this.textBoxBaselineConfig = new TextBox();
			this.labelNotSupported = new Label();
			this.buttonClearTestMem = new Button();
			this.label4 = new Label();
			this.buttonWriteCalWords = new Button();
			this.labelCalWarning = new Label();
			((ISupportInitialize)this.dataGridTestMemory).BeginInit();
			base.SuspendLayout();
			this.dataGridTestMemory.AllowUserToAddRows = false;
			this.dataGridTestMemory.AllowUserToDeleteRows = false;
			this.dataGridTestMemory.AllowUserToResizeColumns = false;
			this.dataGridTestMemory.AllowUserToResizeRows = false;
			this.dataGridTestMemory.BackgroundColor = SystemColors.Window;
			this.dataGridTestMemory.CellBorderStyle = DataGridViewCellBorderStyle.None;
			dataGridViewCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = SystemColors.Control;
			dataGridViewCellStyle.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = DataGridViewTriState.True;
			this.dataGridTestMemory.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.dataGridTestMemory.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.dataGridTestMemory.ColumnHeadersVisible = false;
			dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = SystemColors.Window;
			dataGridViewCellStyle2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = SystemColors.ControlText;
			dataGridViewCellStyle2.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = DataGridViewTriState.False;
			this.dataGridTestMemory.DefaultCellStyle = dataGridViewCellStyle2;
			this.dataGridTestMemory.Location = new Point(16, 52);
			this.dataGridTestMemory.Margin = new Padding(4, 4, 4, 4);
			this.dataGridTestMemory.MultiSelect = false;
			this.dataGridTestMemory.Name = "dataGridTestMemory";
			dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = SystemColors.Control;
			dataGridViewCellStyle3.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle3.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle3.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = DataGridViewTriState.True;
			this.dataGridTestMemory.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this.dataGridTestMemory.RowHeadersVisible = false;
			this.dataGridTestMemory.RowHeadersWidth = 75;
			this.dataGridTestMemory.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridTestMemory.RowsDefaultCellStyle = dataGridViewCellStyle4;
			this.dataGridTestMemory.RowTemplate.Height = 17;
			this.dataGridTestMemory.ScrollBars = ScrollBars.Vertical;
			this.dataGridTestMemory.SelectionMode = DataGridViewSelectionMode.CellSelect;
			this.dataGridTestMemory.Size = new Size(467, 171);
			this.dataGridTestMemory.TabIndex = 5;
			this.dataGridTestMemory.CellEndEdit += new DataGridViewCellEventHandler(this.DataGridTestMemory_CellEndEdit);
			this.label1.AutoSize = true;
			this.label1.Location = new Point(12, 23);
			this.label1.Margin = new Padding(4, 0, 4, 0);
			this.label1.Name = "label1";
			this.label1.Size = new Size(139, 17);
			this.label1.TabIndex = 6;
			this.label1.Text = "Test Memory Words:";
			this.textBoxTestMemSize.Location = new Point(160, 20);
			this.textBoxTestMemSize.Margin = new Padding(4, 4, 4, 4);
			this.textBoxTestMemSize.Name = "textBoxTestMemSize";
			this.textBoxTestMemSize.Size = new Size(64, 22);
			this.textBoxTestMemSize.TabIndex = 7;
			this.textBoxTestMemSize.Leave += new EventHandler(this.TextBoxTestMemSize_Leave);
			this.textBoxTestMemSize.KeyPress += new KeyPressEventHandler(this.TextBoxTestMemSize_KeyPress);
			this.labelTestMemSize8.AutoSize = true;
			this.labelTestMemSize8.ForeColor = Color.Red;
			this.labelTestMemSize8.Location = new Point(233, 16);
			this.labelTestMemSize8.Margin = new Padding(4, 0, 4, 0);
			this.labelTestMemSize8.Name = "labelTestMemSize8";
			this.labelTestMemSize8.Size = new Size(92, 34);
			this.labelTestMemSize8.TabIndex = 22;
			this.labelTestMemSize8.Text = "Must be\r\nmultiple of 16";
			this.labelTestMemSize8.Visible = false;
			this.label11.AutoSize = true;
			this.label11.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.label11.Location = new Point(16, 226);
			this.label11.Margin = new Padding(4, 0, 4, 0);
			this.label11.Name = "label11";
			this.label11.Size = new Size(120, 17);
			this.label11.TabIndex = 23;
			this.label11.Text = "Hex Import-Export";
			this.checkBoxTestMemImportExport.AutoSize = true;
			this.checkBoxTestMemImportExport.Location = new Point(16, 246);
			this.checkBoxTestMemImportExport.Margin = new Padding(4, 4, 4, 4);
			this.checkBoxTestMemImportExport.Name = "checkBoxTestMemImportExport";
			this.checkBoxTestMemImportExport.Size = new Size(161, 21);
			this.checkBoxTestMemImportExport.TabIndex = 24;
			this.checkBoxTestMemImportExport.Text = "Include Test Memory";
			this.checkBoxTestMemImportExport.UseVisualStyleBackColor = true;
			this.checkBoxTestMemImportExport.CheckedChanged += new EventHandler(this.CheckBoxTestMemImportExport_CheckedChanged);
			this.label2.BackColor = Color.LightSteelBlue;
			this.label2.Location = new Point(357, 7);
			this.label2.Margin = new Padding(4, 0, 4, 0);
			this.label2.Name = "label2";
			this.label2.Size = new Size(60, 16);
			this.label2.TabIndex = 25;
			this.label2.Text = "UserIDs";
			this.label3.BackColor = Color.LightSalmon;
			this.label3.Location = new Point(423, 7);
			this.label3.Margin = new Padding(4, 0, 4, 0);
			this.label3.Name = "label3";
			this.label3.Size = new Size(60, 16);
			this.label3.TabIndex = 26;
			this.label3.Text = "Config";
			this.labelBLConfig.AutoSize = true;
			this.labelBLConfig.Location = new Point(307, 246);
			this.labelBLConfig.Margin = new Padding(4, 0, 4, 0);
			this.labelBLConfig.Name = "labelBLConfig";
			this.labelBLConfig.Size = new Size(110, 17);
			this.labelBLConfig.TabIndex = 27;
			this.labelBLConfig.Text = "Baseline Config:";
			this.textBoxBaselineConfig.BackColor = Color.LightSalmon;
			this.textBoxBaselineConfig.Location = new Point(417, 242);
			this.textBoxBaselineConfig.Margin = new Padding(4, 4, 4, 4);
			this.textBoxBaselineConfig.Name = "textBoxBaselineConfig";
			this.textBoxBaselineConfig.Size = new Size(64, 22);
			this.textBoxBaselineConfig.TabIndex = 28;
			this.textBoxBaselineConfig.Text = "0000";
			this.textBoxBaselineConfig.TextAlign = HorizontalAlignment.Center;
			this.textBoxBaselineConfig.Leave += new EventHandler(this.TextBoxBaselineConfig_Leave);
			this.textBoxBaselineConfig.KeyPress += new KeyPressEventHandler(this.TextBoxBaselineConfig_KeyPress);
			this.labelNotSupported.AutoSize = true;
			this.labelNotSupported.BackColor = SystemColors.Info;
			this.labelNotSupported.Font = new Font("Microsoft Sans Serif", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
			this.labelNotSupported.ForeColor = Color.Red;
			this.labelNotSupported.Location = new Point(37, 100);
			this.labelNotSupported.Margin = new Padding(4, 0, 4, 0);
			this.labelNotSupported.Name = "labelNotSupported";
			this.labelNotSupported.Size = new Size(379, 62);
			this.labelNotSupported.TabIndex = 29;
			this.labelNotSupported.Text = "Test Memory Not Supported\r\n            on this family";
			this.labelNotSupported.Visible = false;
			this.buttonClearTestMem.Location = new Point(208, 239);
			this.buttonClearTestMem.Margin = new Padding(4, 4, 4, 4);
			this.buttonClearTestMem.Name = "buttonClearTestMem";
			this.buttonClearTestMem.Size = new Size(67, 28);
			this.buttonClearTestMem.TabIndex = 30;
			this.buttonClearTestMem.Text = "Clear";
			this.buttonClearTestMem.UseVisualStyleBackColor = true;
			this.buttonClearTestMem.Click += new EventHandler(this.ButtonClearTestMem_Click);
			this.label4.BackColor = Color.Gold;
			this.label4.Location = new Point(423, 28);
			this.label4.Margin = new Padding(4, 0, 4, 0);
			this.label4.Name = "label4";
			this.label4.Size = new Size(60, 16);
			this.label4.TabIndex = 31;
			this.label4.Text = "CalWrd";
			this.buttonWriteCalWords.Location = new Point(335, 266);
			this.buttonWriteCalWords.Margin = new Padding(4, 4, 4, 4);
			this.buttonWriteCalWords.Name = "buttonWriteCalWords";
			this.buttonWriteCalWords.Size = new Size(111, 28);
			this.buttonWriteCalWords.TabIndex = 32;
			this.buttonWriteCalWords.Text = "Write CalWrd";
			this.buttonWriteCalWords.UseVisualStyleBackColor = true;
			this.buttonWriteCalWords.Click += new EventHandler(this.ButtonWriteCalWords_Click);
			this.labelCalWarning.AutoSize = true;
			this.labelCalWarning.ForeColor = Color.Red;
			this.labelCalWarning.Location = new Point(323, 226);
			this.labelCalWarning.Margin = new Padding(4, 0, 4, 0);
			this.labelCalWarning.Name = "labelCalWarning";
			this.labelCalWarning.Size = new Size(136, 34);
			this.labelCalWarning.TabIndex = 33;
			this.labelCalWarning.Text = "Writing Cal Words\r\nwill erase ALL Flash!";
			this.labelCalWarning.TextAlign = ContentAlignment.TopCenter;
			this.labelCalWarning.Visible = false;
			base.AutoScaleDimensions = new SizeF(120f, 120f);
			base.AutoScaleMode = AutoScaleMode.Dpi;
			base.ClientSize = new Size(500, 300);
			base.Controls.Add(this.labelCalWarning);
			base.Controls.Add(this.buttonWriteCalWords);
			base.Controls.Add(this.label4);
			base.Controls.Add(this.buttonClearTestMem);
			base.Controls.Add(this.labelNotSupported);
			base.Controls.Add(this.textBoxBaselineConfig);
			base.Controls.Add(this.labelBLConfig);
			base.Controls.Add(this.label3);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.checkBoxTestMemImportExport);
			base.Controls.Add(this.label11);
			base.Controls.Add(this.labelTestMemSize8);
			base.Controls.Add(this.textBoxTestMemSize);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.dataGridTestMemory);
			base.FormBorderStyle = FormBorderStyle.FixedSingle;
			base.Margin = new Padding(4, 4, 4, 4);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "FormTestMemory";
			base.StartPosition = FormStartPosition.CenterScreen;
			this.Text = "Test memory";
			base.FormClosing += new FormClosingEventHandler(this.FormTestMemory_FormClosing);
			((ISupportInitialize)this.dataGridTestMemory).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		private IContainer components;
		private DataGridView dataGridTestMemory;
		private Label label1;
		private TextBox textBoxTestMemSize;
		private Label labelTestMemSize8;
		private Label label11;
		private CheckBox checkBoxTestMemImportExport;
		private Label label2;
		private Label label3;
		private Label labelBLConfig;
		private TextBox textBoxBaselineConfig;
		private Label labelNotSupported;
		private Button buttonClearTestMem;
		private Label label4;
		private Button buttonWriteCalWords;
		private Label labelCalWarning;
	}
}
